### ISSUE TITLE
Is req.Client thread-safe?

### ISSUE THREAD

**Issue by YiuTerran** [imroc/req#101]
Can I create a `req.Client` and use it across all goroutines?

The best practice is what？ If I need to create a new client for every request, how can I open debug log for these clients when debugging?

你好，v3版本的req.Client是线程安全的么？最佳实践是创建一个全局的client，还是每次请求创建一个新的呢？如果是后者的话，怎么统一打开debug日志呢。

是不是考虑EnableDebugLog设置一个func()bool作为参数，这样可以动态的开关所有Client的日志。

**Comment by imroc** [comment]
是线程安全的，不要每个请求都创建client，若没有特殊需求，一般用一个client就行，EnableDebugLog 本身也对本client的所有request生效

**Comment by YiuTerran** [comment]
好的 感谢
