### ISSUE TITLE
No more upload progress in v3?

### ISSUE THREAD

**Issue by maddie** [imroc/req#104]
I'm looking into migrating to v3, but I can't find any way to set a callback in the request for progress reporting.

Is it not yet implemented (planned), or it won't be implemented at all?

**Comment by imroc** [comment]
It has not been implemented yet. Since you need this, I will take the time to implement it today.

**Comment by imroc** [comment]
Both `UploadCallback` and `DownloadCallback` is supported now.

You can show upload progress like this:

```go
client := req.C()
client.R().
	SetFile("excel", "test.xlsx").
	SetUploadCallback(func(info req.UploadInfo) {
        fmt.Printf("%q uploaded %.2f%%\n", info.FileName, float64(info.UploadedSize)/float64(info.FileSize)*100.0)
    }).Post("https://exmaple.com/upload")
/* Output
"test.xlsx" uploaded 7.44%
"test.xlsx" uploaded 29.78%
"test.xlsx" uploaded 52.08%
"test.xlsx" uploaded 74.47%
"test.xlsx" uploaded 96.87%
"test.xlsx" uploaded 100.00%
*/
```

Check documentation [here](https://github.com/imroc/req#Download-Upload).

**Comment by maddie** [comment]
Thanks!!
