### ISSUE TITLE
How to get cookie when response and get value like map

### ISSUE THREAD

**Issue by 631068264** [imroc/req#106]
```go
randomLoginURL := resp.Response.Request.URL.String()
resp, err = common.HttpClient.R().
SetFormData(map[string]string{
	"login":    userName,
	"password": passwd,
}).
Post(randomLoginURL)
if err != nil {
    return
}
cookie := resp.Cookies()
//  cookie len is 0
fmt.Println(cookie)
```

In python
```py
   data = {"login": USERNAME, "password": PASSWORD}
    session.post(response.url, headers=headers, data=data)

    session_value = session.cookies.get_dict().get(session_key)
    if session_value:
        return {session_key: session_value}
```

**Comment by 631068264** [comment]
#51 参考这个可以拿到，但是坑爹呢这是，这么长一串东西

**Comment by imroc** [comment]
这里其实是指的这种场景吧：
1. 客户端发起请求，第一次响应了重定向，响应头里有 cookie
2. 客户端根据重定向再次发起请求，收到响应

然后看 `resp.Cookies()` 的内容，没有第一次响应的内容，如果有内容，是第二次响应的cookie内容。要获取第一个的内容得用
`resp.Request.Response.Cookies()` 去获取。

其实这是http标准库的行为，你可以试下直接用标准库不用`req`，也是这样的。

我的看法是，`resp.Cookies()` 里只带重定向后的响应，重定向之前的响应内容不会有，这是正常的逻辑，没问题。至于为什么 `resp.Request.Response.Cookies()` 能获取到第一次响应的 cookie，这是内部实现细节问题。

**Comment by 631068264** [comment]
哦 好吧，不是bug是feature，你就当我想这么个feature，这无疑更加方便。让用户去数重定向多少次，有点坑爹
