### ISSUE TITLE
How to setup Transport options?

### ISSUE THREAD

**Issue by jorgecuesta** [imroc/req#108]
Hi guys, amazing library and thanks so much for all this hard work!

Now maybe due to my lack of knowledgment on Go I'm unable to figure out how to properly configure Transport with `MaxIdleConns`, `MaxIdleConnsPerHost` and `MaxConnsPerHost`.

Are you able to give me some example please?

**Comment by imroc** [comment]
Currently you can do this:
```go
	client := req.C()
	t := client.GetClient().Transport.(*req.Transport)
	t.MaxIdleConns = 100
	t.MaxIdleConnsPerHost = 2
	t.MaxConnsPerHost = 5
```

In the future, we plan to do some more convenient encapsulation.

**Comment by jorgecuesta** [comment]
Thanks you so much for this example.
