### ISSUE TITLE
建议某些类型数据不要强制下载Body内容写入内存

### ISSUE THREAD

**Issue by woniu369** [imroc/req#11]
https://github.com/imroc/req/blob/master/req.go#L156
```
text|xml|json|javascript|charset|java
```
https://github.com/imroc/req/blob/master/req.go#L295
```
respBody, err := ioutil.ReadAll(reader)
```
我要获取1个txt文件的StatusCode或Header信息,文件大概有1G多,req会强制下载Body内容写入内存.
而我不需要Body内容,只需要返回的StatusCode或Header信息.

**Comment by imroc** [comment]
感谢建议，现已经支持控制不自动下载文本内容的Body写入内存了。API不变，可以通过设置flag来控制，举例：`req.SetFlags(req.LreqHead | req.LrespHead)`  ， 这个本来表示在输出打印的时候允许请求头和响应头被输出，没有响应体，现在`req`发起请求的时候也会检查flag，如果没有`req.LrespBody`就不会自动下载文本Body，只有等到调用`String()`,`Bytes()`,`ToJSON()`,`ToXML()`,`ToFile()`等涉及获取响应内容的方法才会被动读取Body,并且只读一次。

**Comment by woniu369** [comment]
感谢更新
