### ISSUE TITLE
concurrent map iteration and map write

### ISSUE THREAD

**Issue by zhoushun5678** [imroc/req#111]
hi，What's the reason for this：

fatal error: concurrent map iteration and map write

goroutine 179983 [running]:
runtime.throw(0xa75471, 0x26)
	/usr/lib/golang/src/runtime/panic.go:1117 +0x72 fp=0xc00005d7f8 sp=0xc00005d7c8 pc=0x436672
runtime.mapiternext(0xc00005d8e8)
	/usr/lib/golang/src/runtime/map.go:858 +0x54c fp=0xc00005d878 sp=0xc00005d7f8 pc=0x410b2c
net/http.Header.Clone(0xc000358900, 0xa58a96)
	/usr/lib/golang/src/net/http/header.go:102 +0x194 fp=0xc00005d958 sp=0xc00005d878 pc=0x7bac94
github.com/imroc/req/v3.(*Client).do(0xc0002ac900, 0xc0002a0380, 0x0, 0x0, 0x0)
	/root/go/pkg/mod/github.com/imroc/req/v3@v3.9.3/client.go:972 +0x279 fp=0xc00005da50 sp=0xc00005d958 pc=0x8e4cf9
github.com/imroc/req/v3.(*Request).Send(0xc0002a0380, 0xa5844e, 0x3, 0xa7ba15, 0x34, 0x0, 0x0, 0x0)
	/root/go/pkg/mod/github.com/imroc/req/v3@v3.9.3/request.go:393 +0xe5 fp=0xc00005daa0 sp=0xc00005da50 pc=0x90b825
github.com/imroc/req/v3.(*Request).Get(...)
	/root/go/pkg/mod/github.com/imroc/req/v3@v3.9.3/request.go:408

**Comment by imroc** [comment]
This is a edge case, happens when change header in another gorutine during sending request.

**Comment by imroc** [comment]
Fixed in the latest version, you can upgrade: `go get -u github.com/imroc/req/v3`

**Comment by zhoushun5678** [comment]
好的，感谢🤝
