### ISSUE TITLE
bug 设置header请求头时，会自动转化首字母大写？

### ISSUE THREAD

**Issue by SummerSec** [imroc/req#112]
我在设置routing-expression请求头字段时，会自动变成routing-Expression?这是什么原因？还是本身就是这么设计？

这是我需要发送的请求
![image](https://user-images.githubusercontent.com/47944478/164972373-91a2c8f8-22b7-4fea-8f24-b628e8535085.png)

但实际发送的请求是下面这样子？
![image](https://user-images.githubusercontent.com/47944478/164972395-3f633392-ec4d-4f51-b53e-e8ac33eaf49c.png)

**Comment by SummerSec** [comment]
我看了一下源码，默认是会自动改成大写的，但这块能不能支持是否要转化成大写？

**Comment by SummerSec** [comment]
> 我看了一下源码，默认是会自动改成大写的，但这块能不能支持用户自己判断是否要转化成大写？然后默认大写，但用户可以设置不需要转化。

再看发现这是go的sdk的问题。`net/textproto/header.go`

**Comment by SummerSec** [comment]
解决办法如下，直接操作request的header即可。

```go
func main() {

	var req http.Request
	req.Header = map[string][]string{
		"User-Agent":                {"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36"},
		"Accept":                    {"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"},
		"Accept-Encoding":           {"gzip, deflate"},
		"Accept-Language":           {"en-US,en;q=0.9"},
		"Connection":                {"keep-alive"},
		"Upgrade-Insecure-Requests": {"1"},
		"cache-control":             {"max-age=0"},
	}

	req.Method = "GET"
	req.URL = &url.URL{
		Scheme: "https",
		Host:   "www.google.com",
		Path:   "/",
	}

}

```

**Comment by imroc** [comment]
感谢反馈，不过根据 HTTP 规范，HTTP1 的 header，服务端应对大小写不敏感，HTTP2 必须强制转换为小写。不过 HTTP1 确实有不少场景不符合 HTTP 规范，req 这里可以考虑兼容下，这个 PR 功能大致符合，但命名需要改下，我晚点合进去然后我再改一改

**Comment by imroc** [comment]
已合并并修正，最新版已可用(v3.11.0)。
Request level: SetHeaderNonCanonical and SetHeadersNonCanonical.
Client level: SetCommonHeaderNonCanonical and SetCommonHeadersNonCanonical.
