### ISSUE TITLE
could we pass a context with deadline to the request

### ISSUE THREAD

**Issue by slow-zhang** [imroc/req#115]
i want: the job can be cancelled by the upper function or timeout, below is the way that i want to use. could we do it by `imroc/req/`

here is the http.NewRequestWithContext
`func NewRequestWithContext(ctx context.Context, method, url string, body io.Reader) (*Request, error) {`

**Comment by slow-zhang** [comment]
i found SetContext

**Comment by imroc** [comment]
> i found SetContext

Yes, you can use `req.SetContent(ctx)`
