### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by zhoushun5678** [imroc/req#117]
你好，能帮忙看下是啥问题吗？
goroutine 1609 [running]:
github.com/imroc/req/v3.(*Response).Bytes(...)
/root/go/pkg/mod/github.com/imroc/req/v3@v3.10.1/response.go:104

**Comment by zhoushun5678** [comment]
我定义了一个全局的变量，HClient = req.C().SetTimeout(30 * time.Second).R()。然后都是共用的这个client是不是这个问题导致的？

**Comment by SummerSec** [comment]
![image](https://user-images.githubusercontent.com/47944478/168068473-cc5f035b-0dc3-4bf4-a51d-2be580a64273.png)

我也多次遇到这个问题，调用resp.Dump() resp.ToString() resp.String()方法时会出现这种情况。

**Comment by imroc** [comment]
这是 Response 为 nil 导致，只有返回了 error 时 Response 才为 nil，

> 

看报错是调用 `resp.Bytes()` 发生的，这种只能是 Response 为 nil，而正常情况下返回的 `*Response` 永远不为 nil:

```go
// Send fires http request and return the *Response which is always
// not nil, and the error is not nil if some error happens.
func (r *Request) Send(method, url string) (*Response, error) {
```

猜测是存在多个 goroutine 在操作同一个 resp 变量导致，需要结合实际代码分析。

**Comment by SummerSec** [comment]
> http://139.162.180.108:7500

但请求一个不存在的url百分之百为nil的，在我实际使用代码时，并没有存在多个 goroutine 在操作同一个 resp 变量。

**Comment by imroc** [comment]
> ![image](https://user-images.githubusercontent.com/47944478/168068473-cc5f035b-0dc3-4bf4-a51d-2be580a64273.png)
> 
> 我也多次遇到这个问题，调用resp.Dump() resp.ToString() resp.String()方法时会出现这种情况。

截图中是调用 `resp.IsSuccess()` 方法报的错，这种应该是返回了error没处理，直接调用resp判断导致，因为发生error时，虽然resp不为nil，但内部的`*http.Response`是nil，IsSuccess中会判断`*http.Response`的StatusCode，由于是nil所以panic了。这里我可以优化下，即便返回error，IsSuccess也不会panic。

而 resp.Dump() resp.ToString() resp.String() 这些理论上不会发生panic，可以看代码实现，除非是resp变量后来被其它置为了nil，比如前面说的可能其它goroutine操作了这个resp变量。

**Comment by SummerSec** [comment]
![image](https://user-images.githubusercontent.com/47944478/168079122-2a72b6c8-5797-401e-b4d2-a9f5f1a0a896.png)

**Comment by zhoushun5678** [comment]
@imroc 好的，谢谢。 HClient = req.C().SetTimeout(30 * time.Second) 然后会有多个协程操作这个HClient 会有问题吗？

**Comment by SummerSec** [comment]
> ![image](https://user-images.githubusercontent.com/47944478/168079122-2a72b6c8-5797-401e-b4d2-a9f5f1a0a896.png)

这里调用了String()然后就报错了.

**Comment by imroc** [comment]
> @imroc 好的，谢谢。 HClient = req.C().SetTimeout(30 * time.Second) 然后会有多个协程操作这个HClient 会有问题吗？

@zhoushun5678 多个goroutine共用client是可以的哈。

**Comment by imroc** [comment]
注释有点小问题，返回的 string 不可能是 nil，golang  string 类型的零值是""。默认情况，body会被自动读取(命中条件2，即2中的方法没有被调用过)。无论如何，这个跟前面说的问题不相关了

**Comment by imroc** [comment]
IsSuccess, IsError 和 GetContentType 这3个方法依赖了内部的 `*http.Response` 对象，当有error发生时，调用这3个方法可能panic，目前已优化(v3.11.2)
https://github.com/imroc/req/commit/64b3c41fee958bfbdfe01e6f374ed5169b995742

**Comment by imroc** [comment]
正常情况 `resp.String()` 不可能 panic，建议提供复现代码排查下

**Comment by SummerSec** [comment]
> 正常情况 `resp.String()` 不可能 panic，建议提供复现代码排查下

已经排除成功了，是我自己的问题。感谢解答。

**Comment by imroc** [comment]
> > 正常情况 `resp.String()` 不可能 panic，建议提供复现代码排查下
> 
> 已经排除成功了，是我自己的问题。感谢解答。

好的，不客气
