### ISSUE TITLE
大量的网络异常如何规避?

### ISSUE THREAD

**Issue by super-l** [imroc/req#119]
使用场景说明：并发请求多个不同的URL。

配置超时参数与不配置，均会触发此情况。并且关闭程序也不能恢复！
该问题可能不属于库本身的问题，但始终找不到好的解决方案。求解！

{"level":"debug","msg":"提示:Get \"http://www.zhuoooyan.com/\": EOF","time":"05-17 20:28:54"}
{"level":"debug","msg":"提示:Get \"http://www.wxhongguang.com\": context deadline exceeded","time":"05-17 20:28:54"}
{"level":"debug","msg":"提示:Get \"https://www.eyin.cn/\": context deadline exceeded","time":"05-17 20:28:54"}
{"level":"debug","msg":"提示:Get \"http://www.qingangjixie.com\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)","time":"05-17 20:28:54"}
{"level":"debug","msg":"提示:Get \"https://dnspod.qcloud.com/static/webblock.html?d=www.86jobs.com\": context deadline exceeded","time":"05-17 20:28:54"}
{"level":"debug","msg":"提示:Get \"http://www.yunzhenxuan.com/\": context deadline exceeded","time":"05-17 20:28:54"}
{"level":"debug","msg":"提示:Get \"http://www.xfkj1.com\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)","time":"05-17 20:28:54"}
{"level":"debug","msg":"提示:Get \"http://www.guandaojiaozhandai.com/\": context deadline exceeded","time":"05-17 20:28:54"}
{"level":"debug","msg":"提示:Get \"http://www.jbzhb.com\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)","time":"05-17 20:28:54"}
{"level":"debug","msg":"提示:Get \"http://www.zfdzchlj.com/\": net/http: request canceled (Client.Timeout exceeded while awaiting headers)","time":"05-17 20:28:54"}
{"level":"debug","msg":"提示:Get \"http://www.dianshihu.com/\": net/http: request canceled (Client.Timeout exceeded while awaiting headers)","time":"05-17 20:28:55"}
{"level":"debug","msg":"提示:Get \"http://hswsp.cn\": context deadline exceeded","time":"05-17 20:28:56"}
{"level":"debug","msg":"提示:Get \"http://www.szlongdian.net/\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)","time":"05-17 20:28:56"}
{"level":"debug","msg":"提示:Get \"http://www.futongfengji.com\": context deadline exceeded","time":"05-17 20:28:56"}
{"level":"debug","msg":"提示:Get \"http://www.chongkong666.com\": context deadline exceeded","time":"05-17 20:28:56"}
{"level":"debug","msg":"提示:Get \"http://www.nj5666.com/\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)","time":"05-17 20:28:56"}
{"level":"debug","msg":"提示:Get \"http://www.cuplmsy-edu.cn/\": context deadline exceeded","time":"05-17 20:28:56"}
{"level":"debug","msg":"提示:Get \"https://www.ifoam.bio/\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)","time":"05-17 20:28:57"}
{"level":"debug","msg":"提示:Get \"http://www.yuyantiyu.com\": read tcp 192.168.1.4:8940-\u003e34.98.99.30:80: wsarecv: An existing connection was forcibly closed by the remote host.","time":"05-17 20:28:57"}

**Comment by imroc** [comment]
先确保服务端有没有问题，如果没问题，一般是客户端网络环境本身的问题，比如网络抖动与丢包，考虑调优内核参数和调高公网带宽

**Comment by super-l** [comment]
没有服务端。或者说是开放公网WEB服务的所有网站地址。在程序里面请求出大量异常，但是用浏览器或者curl或者postman之内的却正常。

程序里面是多个协程，通过channel实现的类似消息队列的协程池。不知道是不是请求太快导致的。加上sleep也不行比较奇怪。

**Comment by lingxiao00** [comment]
你好 这个问题有解决吗
