### ISSUE TITLE
好奇 为何 DevMode 模式下 要设置带入默认 UserAgent

### ISSUE THREAD

**Issue by puzzle9** [imroc/req#120]

**Comment by imroc** [comment]
有些网站或接口会检测 `User-Agent` 的头，不是浏览器不给正常响应，DevMode 主要为了方便测试，加这个可以提高成功率

**Comment by Xwudao** [comment]
> 有些网站或接口会检测 `User-Agent` 的头，不是浏览器不给正常响应，DevMode 主要为了方便测试，加这个可以提高成功率

成功率提高了，运维一看就是爬虫😭
