### ISSUE TITLE
建议添加一个清空cookies的方法

### ISSUE THREAD

**Issue by Nyx2022** [imroc/req#127]
连续的响应一般会从response中获取set-cookie字段，并应用在下一次的request header中，但是有些情况下是不需要携带cookie，我去尝试了reqReq.SetCookies(&http.Cookie{})和reqReq.SetCookies(nil)，发现最终cookie对呗带到了reqeust中，所以建议添加一个方法选择不带所有cookie信息的方法？

**Comment by imroc** [comment]
这是因为默认有CookieJar，当server有Set-Cookie时，就把cookie规则存下来，像浏览器一样，下次访问时带上Cookie。如果不需要可以不用CookieJar:
```go
client.SetCookieJar(nil)
```

**Comment by Nyx2022** [comment]
> 这是因为默认有 CookieJar，当 server 有 Set-Cookie 时，就把 cookie 规则存下来，像浏览器一样，下次访问时带上 Cookie。如果不需要可以不用 CookieJar:
> 
> ```go
> client.SetCookieJar(nil)
> ```

SetCookieJar是client级别的方法，假设多个请求公用一个reqClient，第二个request不需要携带cookie，但是第三个需要携带第二个或第一个resposne返回的cookie，能满足这种场景吗

**Comment by imroc** [comment]
> SetCookieJar是client级别的方法，假设多个请求公用一个reqClient，第二个request不需要携带cookie，但是第三个需要携带第二个或第一个resposne返回的cookie，能满足这种场景吗

这种场景建议分不同client去发送request，需要cookie的用一个client，不需要的用另一个

**Comment by Nyx2022** [comment]
> > SetCookieJar 是 client 级别的方法，假设多个请求公用一个 reqClient，第二个 request 不需要携带 cookie，但是第三个需要携带第二个或第一个 resposne 返回的 cookie，能满足这种场景吗
> 
> 这种场景建议分不同 client 去发送 request，需要 cookie 的用一个 client，不需要的用另一个

这样的话不就占用资源了嘛，而且2个client之间能不能保证无缝衔接，还是一个问题，所以还是建议将SetCookieJar 在request上提供一个替代方法

**Comment by imroc** [comment]
仅仅是多一个client，简单的判断下而已。即使只用一个client，在request级别上控制是否需要cookie，一样的要判断，差别不大

**Comment by Nyx2022** [comment]
> 仅仅是多一个client，简单的判断下而已。即使只用一个client，在request级别上控制是否需要cookie，一样的要判断，差别不大

始终还是建议添加对应的api以满足对应的场景

**Comment by imroc** [comment]
> 始终还是建议添加对应的api以满足对应的场景

这个比较难实现，目前市面上没有哪个client这么干，这个client基于标准库http.Client，CookieJar的控制本身只在client级别。
