### ISSUE TITLE
没有自动解压响应报文？

### ISSUE THREAD

**Issue by Nyx2022** [imroc/req#129]
我的一个http请求，服务器端返回的resposne的header里面指明了gzip压缩，但是我使用res.string或res.bytes得到的是压缩内容，而不是自动解压缩之后的内容。我看到DisableCompression()方法的注释里面以为req能够自动解压内容，但是发现好像不是，希望添加一个能够自动解压响应正文的方法

**Comment by imroc** [comment]
```go
package main

import (
	"github.com/imroc/req/v3"
)

func main() {
	req.DevMode()
	req.MustGet("https://baidu.com")
}
```

![图片](https://user-images.githubusercontent.com/7448852/174741958-65fed464-2e39-4b29-8dbd-e7b80eb7dfd6.png)

是有自动解压的，可以看看服务端的response header是否正确

**Comment by Nyx2022** [comment]
> ```go
> package main
> 
> import (
> 	"github.com/imroc/req/v3"
> )
> 
> func main() {
> 	req.DevMode()
> 	req.MustGet("https://baidu.com")
> }
> ```
> 
> ![图片](https://user-images.githubusercontent.com/7448852/174741958-65fed464-2e39-4b29-8dbd-e7b80eb7dfd6.png)
> 
> 是有自动解压的，可以看看服务端的 response header 是否正确

![image](https://user-images.githubusercontent.com/51039208/174750058-2f7c300b-7182-4149-b9d4-acca3db51cba.png)

我的请求响应是这样的，确实没有自动解压

**Comment by imroc** [comment]
> ![image](https://user-images.githubusercontent.com/51039208/174750058-2f7c300b-7182-4149-b9d4-acca3db51cba.png)
> 
> 我的请求响应是这样的，确实没有自动解压

看这个明显解压了，只是乱码而已，看header是GBK编码，按理应该也会自动转码成utf8，这个server可以公开访问么，我试试

**Comment by Nyx2022** [comment]
> 

这个没办法公开访问，如果你解决了转码问题，可以回复我，然后我再试下，跟你同步一下是否解决这个问题

**Comment by imroc** [comment]
我猜测是server响应的Content-Type的 charset 是 GBK，但实际body内容返回的编码不是GBK，就可能造成这种混乱

**Comment by imroc** [comment]
如果response如之前截图一样，应该会有类似 `charset GBK detected in Content-Type, auto-decode to utf-8`，测试代码:
```go
package main

import (
	"github.com/imroc/req/v3"
)

func main() {
	client := req.C().EnableDebugLog().EnableDumpAllWithoutResponseBody()
	client.R().Get("http://baidu.com/s?wd=req")
}
```

```txt
2022/06/21 21:27:24.319363 DEBUG [req] HTTP/1.1 GET http://baidu.com/s?wd=req
GET /s?wd=req HTTP/1.1
Host: baidu.com
User-Agent: req/v3 (https://github.com/imroc/req)
Accept-Encoding: gzip

HTTP/1.1 302 Found
Age: 20
Cache-Control: max-age=86400
Content-Length: 213
Content-Type: text/html; charset=iso-8859-1
Date: Tue, 21 Jun 2022 13:27:04 GMT
Expires: Wed, 22 Jun 2022 13:27:04 GMT
Location: http://www.baidu.com/s?wd=req
Server: Apache
X-Cache: HIT from CD-SQUIDWEB-30
X-Cache-Lookup: HIT from CD-SQUIDWEB-30:8080

2022/06/21 21:27:24.430442 DEBUG [req] charset iso-8859-1 detected in Content-Type, auto-decode to utf-8

```
