### ISSUE TITLE
BodyJSON和BodyXml的个人看法

### ISSUE THREAD

**Issue by Owen-Zhang** [imroc/req#13]
你传参数的方式很好，只是没有具体研究过这种方式(v.(type))是否有些性能影响。

在工作中也在用这个package,  谈下我的个人想法：
在传实体(json,xml)时，能否通过header去判断而不是用 BodyJSON等方式
req.Post(url, req.BodyJSON(&foo))

如：
//数据实体
type ReqData struct {
	v interface{}
}

//在外边用的时候，传入header
req.Header{
	"Accept":        "application/json",　//可以写一些公共的，大家直接用就可以了
       "Content-Type": "application/json",
}

//在POST提交的方法中，通过判断header去完成不同的序列化

//同时返回也可以通过header去判断完成反序列化，不过相应的结构会有些调整

**Comment by imroc** [comment]
1.BodyJSON在序列化同时也会自动设置Content-Type，简化代码。您说的方式不是不可以，只是我看来使用上容易产生歧义，不够明确、简洁和优雅，持保留意见。

2.v.(type)这种方式对性能影响忽略不计，不过还可以更优雅，打算用[Functional Options](https://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis)的风格实现，API可以不用改变，但会带来一些好处（易扩展、修改等），准备后面有空来实现。
