### ISSUE TITLE
client并发不安全

### ISSUE THREAD

**Issue by Nyx2022** [imroc/req#130]
我使用ants在大量goroutines中使用req，但是req好像不是goroutine安全的，或者是底层级制还不够完善。所以没办反承受这种使用场景，建议强力优化

![image](https://user-images.githubusercontent.com/51039208/176080445-0a23c2c4-e274-4418-b6d9-5c8010cda7f1.png)

**Comment by imroc** [comment]
看起来是在多个goroutine里并发修改同一client的配置，有些方法是线程不安全的，比如并发设置header。

一般是用法问题，对于同一个client，没必要并发修改和设置，如果默认加锁，开销较大。

**Comment by Nyx2022** [comment]
> 看起来是在多个goroutine里并发修改同一client的配置，有些方法是线程不安全的，比如并发设置header。
> 
> 一般是用法问题，对于同一个client，没必要并发修改和设置，如果默认加锁，开销较大。

所以建议改成goroutine安全的，这样可能会满足更多用户的需求

**Comment by imroc** [comment]
> 所以建议改成goroutine安全的，这样可能会满足更多用户的需求

没有哪个client是这么干的，改成goroutine安全很简单，但这会损失很大性能。根本还是用法问题，client不应该被并发设置。

**Comment by imroc** [comment]
实在有需求可以自行加锁设置

**Comment by shadow1ng** [comment]
> 并发设置header

如果是扫描器，会需要频繁并发设置header吧

**Comment by imroc** [comment]
> 如果是扫描器，会需要频繁并发设置header吧

不同请求header不一样，那也是在request级别设置，每个goroutine都用`R()`创建的request是互不相干的对象，不共享，也不存在并发设置的情况

**Comment by shadow1ng** [comment]
好的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: roc ***@***.***&gt;
发送时间: 2022年8月3日 19:46
收件人: imroc/req ***@***.***&gt;
抄送: 影舞者 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [imroc/req] client并发不安全 (Issue #130)





  
如果是扫描器，会需要频繁并发设置header吧
  
不同请求header不一样，那也是在request级别设置，每个goroutine都用R()创建的request是互不相干的对象，不共享，也不存在并发设置的情况
