### ISSUE TITLE
Expose the client log to be used in middleware?

### ISSUE THREAD

**Issue by nomad-software** [imroc/req#132]
Hi, thanks for the great library!

Is there any way I can use the client log in middleware? I know we can set the logger using `client.SetLog(...)` but it would be nice to use this later.

Because the client `log` field is not exported I have to do something like this to enable a log in middleware:

```
func LogRequest(log req.Logger) req.RequestMiddleware {
    return func(c *req.Client, r *req.Request) error {
        log.Debugf("%s request, path: %s, retry attempt: %d",
            r.Method,
            r.URL.RequestURI(),
            r.RetryAttempt,
        )
        return nil
    }
}
...
client := req.C().
    SetLog(logger).
    client.OnBeforeRequest(middleware.LogRequest(logger))
```

It would be nice to just do this:
```
func LogRequest(c *req.Client, r *req.Request) error {
    c.Log.Debugf("%s request, path: %s, retry attempt: %d",
        r.Method,
        r.URL.RequestURI(),
        r.RetryAttempt,
    )
    return nil
}
...
client := req.C().
    SetLog(logger).
    client.OnBeforeRequest(middleware.LogRequest)
```
Thoughts?

**Comment by imroc** [comment]
Good idea, expose `Client.Logger()` would be more appropriate, but there has been a major refactoring recently. In order to avoid code conflicts, I will support this after the http3 support is released.

Check this out: https://req.cool/blog/http3-support-is-coming/

**Comment by nomad-software** [comment]
Cool, thanks!

**Comment by imroc** [comment]
`v3.14.0` is released, now you can use `Client.GetLogger()` to get the logger.

**Comment by nomad-software** [comment]
Awesome, Thankyou!
