### ISSUE TITLE
如何去掉RN [req] cannot determine the unmarshal function with "application/x-javascript" Content-Type, default to jsonde 的提示

### ISSUE THREAD

**Issue by birdycn** [imroc/req#133]
请求的接口没有返回contenttype，然后req总是提示这个，有点烦人。
RN [req] cannot determine the unmarshal function with "application/x-javascript" Content-Type, default to json

**Comment by imroc** [comment]
client.SetLogger(nil)

**Comment by imroc** [comment]
后面打算将这个级别降到debug，默认不输出，等 http3支持发布后再调整

**Comment by imroc** [comment]
最新版已调整至debug级别

**Comment by birdycn** [comment]
谢谢哦
