### ISSUE TITLE
v1 版本中, 使用全局的req.SetTimeout(), 每次发送请求时设置timeout, 高并发的情况下,timeout值会被覆盖吗?

### ISSUE THREAD

**Issue by goodboy3** [imroc/req#135]
v1 版本中, 如果每次请求都使用 req.New() 创建一个新的client, 发现这样就无法复用之前建立的链接,每次都需要重新握手. 因此我改用全局的req.Post() 来发送请求.每次发送请求时设置timeout, 高并发的情况下,timeout值会被覆盖吗?

**Comment by imroc** [comment]
不会覆盖。如果每次都使用 req.New() 创建新client，就需要每次都设置。v1不维护了，建议升级到v3

**Comment by goodboy3** [comment]
了解,多谢
