### ISSUE TITLE
Support response middleware executed even error is not nil

### ISSUE THREAD

**Issue by imroc** [imroc/req#140]

**Comment by ETZhangSX** [comment]
This is an important feature. For now, I might miss some prometheus metrics if some errors occur.

**Comment by imroc** [comment]
Well, this was actually planned to be supported before, and it is very necessary in some scenarios, such as recording metrics and tracing. Since you need this feature, I will raise the priority and support it immediately.

**Comment by imroc** [comment]
Now you can upgrade to the latest version:

```bash
go get -u github.com/imroc/req/v3
```

`ResponseMiddleware` will be executed even if error occurs, users can choose whether to skip inside the middleware function:

```go
	client := req.C().OnAfterResponse(func(c *req.Client, resp *req.Response) error {
		if resp.Err != nil { // skip if error occurs.
			return nil
		}
		...
	})
```

If you don't want to skip (still recording metrics when err occurs), you don't need change anything at all.

**Comment by ETZhangSX** [comment]
Great 👍. But there were some panic in my service when I updated it from `v3.13.2` to `v3.14.3` earlier. It seems like something went wrong in `transport.go` when the number of concurrency is high. I will raise another issue for detail later when free.

**Comment by imroc** [comment]
> Great 👍. But there were some panic in my service when I updated it from `v3.13.2` to `v3.14.3` earlier. It seems like something went wrong in `transport.go` when the number of concurrency is high. I will raise another issue for detail later when free.

@ETZhangSX Are you setting up the same client or request in multiple goroutines concurrently?

**Comment by ETZhangSX** [comment]
> > Great 👍. But there were some panic in my service when I updated it from `v3.13.2` to `v3.14.3` earlier. It seems like something went wrong in `transport.go` when the number of concurrency is high. I will raise another issue for detail later when free.
> 
> @ETZhangSX Are you setting up the same client or request in multiple goroutines concurrently?

@imroc yes, I wrap an SDK like which is suggested in https://req.cool/docs/examples/build-sdk-quickly-with-req. And I initial an global instance for usage. But this in `v1.13.2` is OK. Do I need to use `c.Clone()` to create a new client for each request?

**Comment by ETZhangSX** [comment]
For each request, I wrap a function to set up the client as following.  If I need to set up the client, I will use `Clone()` to create a new client.  So I think it may be not cause by this.

```go
func loadOptions(c *req.Client, opts []Option) *req.Client {
	if len(opts) == 0 {
		return c
	}
	c = c.Clone()
	for _, opt := range opts {
		opt(c)
	}
	return c
}
```

**Comment by imroc** [comment]
You can try to reproduce it, and then paste the panic stack error here.

**Comment by ETZhangSX** [comment]
> You can try to reproduce it, and then paste the panic stack error here.

Sorry for the late reply, I busy these days. I created a new issue, refer to #157
