### ISSUE TITLE
read on closed response body

### ISSUE THREAD

**Issue by nbwzlyd** [imroc/req#142]
想用你的框架请求接口，然后再用goquery框架进行爬虫，但是会报上述错误read on closed response body，我尝试用ioutil.ReadAll(res.Body)
resbody := ioutil.NopCloser(bytes.NewReader(bodyRes))
方法再生成可读res，但是应该是我用法不对依然没得到我想要的结果，（好像结果是空）

原生http一切正常，所以我改怎么做呢，
我是个初学者，谢谢作者

**Comment by nbwzlyd** [comment]
client := req.C().DevMode()
	headersMap := map[string]string{"Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
		"Cookie": "_ga=GA1.2.939129307.1658041785; _gid=GA1.2.2123549520.1658041785; Hm_lvt_667639aad0d4654c92786a241a486361=1658041785; likes=; Hm_lpvt_667639aad0d4654c92786a241a486361=1658042727"}
	client.SetCommonHeaders(headersMap).
		SetUserAgent("Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Mobile Safari/537.36")

	res, err := client.R().SetQueryParam("p", pageNum).
		Get("https://bing.ioliu.cn/?")
	//res, err := http.Get("https://bing.ioliu.cn/?p=2")
	if err != nil {
		fmt.Println("请求异常")
		return bean.BaseJsonBean{
			Code: 1002, Data: nil, Message: "接口异常",
		}
	}
	defer res.Body.Close()

	doc, err := goquery.NewDocumentFromReader(res.Body)
	if err != nil {
		fmt.Println("数据解析异常" + err.Error())
		return bean.BaseJsonBean{
			Code: 1002, Data: nil, Message: "数据解析异常",
		}
	}

**Comment by imroc** [comment]
req默认会读取`res.Body`并close，所以将它传给goquery的是已经读取过的Body，goquery再读一遍，自然就会报错。

可以禁用自动读取:
```go
client.DisableAutoReadResponse()
```

详见: https://req.cool/docs/tutorial/read-response/#auto-read-response-body

**Comment by nbwzlyd** [comment]
非常感谢
