### ISSUE TITLE
req post 提示  "text/html;charset=UTF-8" Content-Type, default to json

### ISSUE THREAD

**Issue by WyntersN** [imroc/req#143]
2022/07/28 15:51:41.665308 WARN [req] cannot determine the unmarshal function with "text/html;charset=UTF-8" Content-Type, default to json

这种情况怎么解决？

**Comment by imroc** [comment]
这是因为服务端返回了html类型内容，但客户端又想将其反序列化成struct或map(调用了SetResult或resp.Unmarshal)，默认使用json反序列化（如果没失败，通常是服务端返回的content-type不准确，所以warning)；这个在最新的提交里，已经将这条log调到debug级别，默认不输出了，只是还没release，我现在就release下。

**Comment by imroc** [comment]
已经 release 到 v3.14.1，可以更新下:
```bash
go get -u github.com/imroc/req/v3
```

**Comment by WyntersN** [comment]
服务端返回协议：content-type:text/html;charset=UTF-8，Body又是 JSON类型，这种情况 Body 是否能进行反序列化成struct
