### ISSUE TITLE
关于  SetProxyURL 遇到的问题

### ISSUE THREAD

**Issue by WyntersN** [imroc/req#145]
在进行 SetProxyURL 的时候传入空Proxy信息 无法进行正常req，所以能不能 SetProxyURL 函数 做个判断，传入空参数就不去执行SetProxyURL

**Comment by WyntersN** [comment]
还有  res.String() 获取到的是：{}，当我 res.String()==“{}”  进行对比后怎么是false；

**Comment by imroc** [comment]
> 在进行 SetProxyURL 的时候传入空Proxy信息 无法进行正常req，所以能不能 SetProxyURL 函数 做个判断，传入空参数就不去执行SetProxyURL

多谢反馈，发现这是标准库 url.Parse("") 传入空串不会返回error，我已经加了判断，已release到v3.14.2，可以更新一下:
```bash
go get -u github.com/imroc/req/v3
```

**Comment by imroc** [comment]
> 还有 res.String() 获取到的是：{}，当我 res.String()==“{}” 进行对比后怎么是false；

应该是有啥特殊字符或空白的，可以打印十六进制对比下:
```go
fmt.Printf("%x\n", "{}")
fmt.Printf("%x\n", resp.Bytes())
```

**Comment by WyntersN** [comment]
res.Bytes() 多了十六进制 0a

**Comment by WyntersN** [comment]
res.Bytes() 转16进制 多了 0a

**Comment by WyntersN** [comment]
多线程的时候 是不是不推荐.R()每次都修改SetHeader吗?

**Comment by WyntersN** [comment]
多线程的时候 是不是不推荐.C() 和 R()每次都修改SetHeader吗?

1、假如.C().SetProxyURL  我一个线程需要一个不同的Proxy ，这时候我就需要.C().SetProxyURL 修改代理信息，多线程并发的时候是不是会触发到不安全。
2、假如.R().SetHeader ，设置head Token，每个线程都是不同的token，这样我又需要去.R().SetHeader ，多线程并发是不是也会触发到不安全。

**Comment by imroc** [comment]
> res.Bytes() 转16进制 多了 0a

0x0a 在 ASCII 编码表示换行符 `\n`。

判断的时候可以用 `strings.Contains()` 函数，不用 `==` 比较。

**Comment by imroc** [comment]
不管是`C()`创建的client还是`R()`创建的 reqeust，都尽量不要并发修改

`C()` 是创建 client，不建议每次都创建新的 client，通用只需要创建一个 client 即可，参考最佳实践: https://req.cool/zh/docs/tutorial/best-practices/

对于 `R()` ，如果每个 gorouting 都用 `R()` 创建了 request，它们并发设置 request 是互不影响的，因为都是创建的单独 request，通常也不会有多个goroutine并发修改同一个request的场景

**Comment by imroc** [comment]
如果是所有请求都共有的属性，可以考虑在 client 级别设置，比如:
```go
client.SetCommonHeader("Authorization", "Berear xxxx")
```

**Comment by WyntersN** [comment]
谢谢，已经明白了
