### ISSUE TITLE
SetFormData 的参数只能map[string]string吗？

### ISSUE THREAD

**Issue by xdkaka** [imroc/req#148]
可不可以map[string]int 或者map[string]interface{}呢

**Comment by imroc** [comment]
目前只能 `map[string]string`，不过如果改成 `map[string]interface{}` 倒也是能兼容的，但就需要内部默认用 `fmt.Sprint` 转换成 string，大多情况可能不需要，增加不必要的性能开销。

针对需要这种有需要的场景，可以考虑增加一个函数 `SetFormDataAnyType`，接收 `map[string]interface{}`，内部自动将 interface{} 转成 string。

**Comment by imroc** [comment]
我准备增加这个函数，一会儿就发布，升级到最新版就可以用

**Comment by imroc** [comment]
可以更新到最新版使用了:
```bash
go get -u github.com/imroc/req/v3
```
```go
client := req.C()
resp, err := client.R().SetFormDataAnyType(map[string]int{"test": 1}).Post(url)
```

**Comment by xdkaka** [comment]
666

**Comment by xdkaka** [comment]
看了下你的代码，SetFormDataAnyType在内部做了个格式转化

是表单提交的都是string类型吗？

提交JSON数据的话，里面的字段是有强类型校验的

**Comment by imroc** [comment]
> 看了下你的代码，SetFormDataAnyType在内部做了个格式转化
> 
> 是表单提交的都是string类型吗？
> 
> 提交JSON数据的话，里面的字段是有强类型校验的

http表单是key value形式，都是string。一般提交json不用表单，调用SetBody传入结构体或map自动转json

**Comment by imroc** [comment]
https://req.cool/docs/tutorial/set-body/

**Comment by xdkaka** [comment]
了解了，感谢
