### ISSUE TITLE
post请求失败，无法恢复

### ISSUE THREAD

**Issue by cobain** [imroc/req#150]
业务上有个请求，post，会不断的循环请求，但是当遇到某个失败后，貌似请求就会一直返回这个错误，直到重启go进程，post请求就正常了。用的req的0.2.4版本。不知道是否和req有关。

**Comment by cobain** [comment]
正常情况下，失败了。下次请求当服务正常后，也是正常执行，但是就是当重复了很多次，突然某个奇怪的错误，就卡住了。
目前已经打开debug开关。看看是否能捕捉一些信息。

**Comment by imroc** [comment]
升级到最新版吧，0.2.4太老了，不维护了

**Comment by imroc** [comment]
v3文档 https://req.cool/zh

**Comment by cobain** [comment]
嗯，我今天看看升级，我只是对这个问题很好奇，在老版本中，我是否能解决这个问题呢

**Comment by cobain** [comment]
因为我请求失败后，睡眠了一段时间也加了。就是不行，重启go进程后，立马就可以，我感觉是不是哪里死锁了。或者说重复使用了缓存等。目前先升级到0.3.2了

**Comment by imroc** [comment]
建议升级到v3，0.xx 不维护了

**Comment by imroc** [comment]
v3有不兼容改动，但强大很多倍

**Comment by cobain** [comment]
好的，我可以两者并存吧。因为目前就一个请求老出问题，我可以先把一个换了。立马到线上测试观察了。

**Comment by cobain** [comment]
先升级了。跑跑看，就怕升级还是有问题。底层的问题。

**Comment by imroc** [comment]
> 好的，我可以两者并存吧。因为目前就一个请求老出问题，我可以先把一个换了。立马到线上测试观察了。

@cobain 可以的，import 路径不同，不影响

**Comment by cobain** [comment]
嗯，好，已经升级了几个请求了。先试试看

**Comment by cobain** [comment]
周末又出了一次这个问题，我全部升级了。再观察观察。 不过可以想想V3上是否会有这个问题。

**Comment by cobain** [comment]
我以前用的fasthttp，也是不断的跑，但是接口不同，倒是没出现过。

**Comment by cobain** [comment]
问题又出现了。log我打印了。是请求突然返回了一个404错误，然后请求都挂了。会不会是request复用造成的问题？

**Comment by imroc** [comment]
应该不相干，看看访问的url是什么，为什么server响应404吧，可以借助v3强大的debug能力看看 https://req.cool/zh/docs/tutorial/debugging/

可以结合中间件和dump能力，在异常时将原始请求内容完整dump下来并打印 https://req.cool/zh/docs/examples/handle-exceptions-with-middleware/

**Comment by cobain** [comment]
我已经打印了。看着请求都正常，和请求正确的时候请求一样的，就是突然报错后，就无法恢复了。
404是第三方api返回的结果，如果发生错误，我这边会继续请求。404是偶发，也许是对方部署或者网关的问题，我们不需要关心。还有很奇怪的是，当我重启后，立即就返回正确了。

**Comment by imroc** [comment]
得联合服务端一起排查了，server响应的404，明显跟server行为有关了

**Comment by cobain** [comment]
这是第三方，但是这个错误后，按道理我的逻辑，下一次或者请求多次，就应该成功了。现在的问题是，一旦错误发生，就一直是这个错误。这是问题的关键。

**Comment by cobain** [comment]
我用的一个全局的client，我试试报错后，重新创建一个client看看

**Comment by cobain** [comment]
后面我自己看吧。v3的功能确实强大。我增加一下retry逻辑里面尝试清除cookie等，试试。

**Comment by imroc** [comment]
像是server端的某个诡异逻辑，比如连接复用时，达到某个条件后，此连接后续请求都响应404。
或者判断cookie，特定条件下带特定cookie都响应404

**Comment by cobain** [comment]
有可能是吧。我也是分析了dump log，感觉有可能是这个问题，不然重启为啥就直接好了呢？
按照这个思路，我改好了。重新创建client，目前不知道这样清理cookie是否能work，所以干脆先创建了。你看看我这样清理cookie对吗，貌似也没发现其他办法。
	GlobalClient.SetCookieJar(nil)
	GlobalClient.Cookies = nil

**Comment by imroc** [comment]
Client.SetCookieJar(nil) 表示禁用cookie，所有请求都不会自动带cookie。
Client.Cookies 是存的 Client.SetCommonCookies 中传入的 cookie，表示给所有请求都带上这些cookie，默认为空。

**Comment by imroc** [comment]
如果是清空cookie，可以这样做：
```go
jar, _ := cookiejar.New(&cookiejar.Options{PublicSuffixList: publicsuffix.List})
GlobalClient.SetCookieJar(jar)
```

如果实际根本不需要cookie，可以禁用:
```go
GlobalClient.SetCookieJar(nil)
```

**Comment by cobain** [comment]
好的，我回头试试禁用，你上面提到的这个清空我先试试，publicsuffix.List 这个如何给值呢。

**Comment by imroc** [comment]
> 好的，我回头试试禁用，你上面提到的这个清空我先试试，publicsuffix.List 这个如何给值呢。

@cobain List 是 `golang.org/x/net/publicsuffix` 的全局变量

**Comment by cobain** [comment]
多谢。了解了。我看小写，还以为要自己给个值，😄。
我再观察观察，通过这个问题，req v3整个文档和源码翻了一遍，😂。

**Comment by imroc** [comment]
👍

**Comment by cobain** [comment]
好像是解决了。但是感觉retry hook的方法没进来，中间打印的日志也没看到。
最后通过http status code判断，清除cookie，然后也重新创建client，目前ok

**Comment by imroc** [comment]
retry hook没执行？检查下 retry condition 设置没有，默认是只有 error 才 retry，404 不是error，可以自定义:
```go
var GlobalClient *req.Client

func initClient() {
	GlobalClient = req.C().EnableDumpEachRequest().
		SetCommonRetryCount(1).
		SetCommonRetryCondition(func(resp *req.Response, err error) bool {
			return err != nil || !resp.IsSuccess()
		}).
		SetCommonRetryHook(func(resp *req.Response, err error) {
			initClient()
		})
}

func init() {
	initClient()
}
```

**Comment by imroc** [comment]
我理解重建client只是临时规避，建议还是查下根因，对症下药

**Comment by imroc** [comment]
欢迎加群交流，昨天刚创建

## Contact

If you have questions, feel free to reach out to us in the following ways:

* [Github Discussion](https://github.com/imroc/req/discussions)
* [Slack](https://imroc-req.slack.com/archives/C03UFPGSNC8) (International) | [Join](https://slack.req.cool/)
* QQ Group (Chinese): 621411351 - <a href="https://qm.qq.com/cgi-bin/qm/qr?k=P8vOMuNytG-hhtPlgijwW6orJV765OAO&jump_from=webapi"><img src="https://pub.idqqimg.com/wpa/images/group.png"></a>
