### ISSUE TITLE
Go1.19 qtls报错，无法编译

### ISSUE THREAD

**Issue by WyntersN** [imroc/req#151]
go version go1.19 amd64

# github.com/imroc/req/v3/internal/qtls
../../pkg/mod/github.com/imroc/req/v3@v3.14.2/internal/qtls/go119.go:13:2: ConnectionState redeclared in this block
	../../pkg/mod/github.com/imroc/req/v3@v3.14.2/internal/qtls/go118.go:13:2: other declaration of ConnectionState
../../pkg/mod/github.com/imroc/req/v3@v3.14.2/internal/qtls/go119.go:17:6: ToTLSConnectionState redeclared in this block
	../../pkg/mod/github.com/imroc/req/v3@v3.14.2/internal/qtls/go118.go:17:6: other declaration of ToTLSConnectionState

**Comment by imroc** [comment]
req升级到最新就可以了

**Comment by WyntersN** [comment]
早说嘛，我还降级了
