### ISSUE TITLE
req should restore `response.Body` when AutoReadResponse is enabled 

### ISSUE THREAD

**Issue by abdusco** [imroc/req#152]
I lost an hour to debugging this issue today https://github.com/imroc/req/issues/142. I was trying to stream responses directly to a `http.ResponseWriter`.

When I realized that everything works without any problem when I switch to `http.Client`, I figured out what was happening, and remembered reading about `DisableAutoReadResponse` method.

An alternative solution to using `DisableAutoReadResponse` is to restore the response body:

https://github.com/imroc/req/blob/6984f39aca47dedeb33f1bdd089876f4d07f08db/client.go#L1188-L1194

if you restore the body back to a `ReadCloser`, this should get rid of the unexpected `read on closed response body` error entirely

```golang
if !c.disableAutoReadResponse && !r.isSaveResponse {
	_, err = resp.ToBytes()
	if err != nil {
		return
	}
	// restore body for re-reads
	resp.Body = io.NopCloser(bytes.NewReader(resp.body))
}
```

**Comment by abdusco** [comment]
Here's a test case to replicate the issue:

```golang
func TestRestoreBody(t *testing.T) {
	s := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte("something"))
	}))
	defer s.Close()

	t.Run("typical usage, no re-reads", func(t *testing.T) {
		c := req.C().EnableAutoReadResponse()
		res, err := c.R().Get(s.URL)
		assert.NoError(t, err)
		defer res.Body.Close()

		var buf bytes.Buffer
		_, err = io.Copy(&buf, res.Body)
		assert.Errorf(t, err, "http: read on closed response body")
	})

	t.Run("typical usage, restored body", func(t *testing.T) {
		c := req.C().EnableAutoReadResponse()
		res, err := c.R().Get(s.URL)
		assert.NoError(t, err)
		defer res.Body.Close()
		// restore
		res.Body = io.NopCloser(bytes.NewReader(res.Bytes()))

		var buf bytes.Buffer
		_, err = io.Copy(&buf, res.Body)
		assert.NoError(t, err)
	})
}
```

**Comment by imroc** [comment]
Nice catch, but what is the scenario that requires both automatic reading of the body and manual reading?

**Comment by imroc** [comment]
Now that this is supported, you can update to the latest version.

**Comment by abdusco** [comment]
> Nice catch, but what is the scenario that requires both automatic reading of the body and manual reading?

I wanted to stream the response body. I wasn't aware that auto reading of responses were enabled by default. So I kept getting `http: read on closed response body` even though I shouldn't have been.

This meant that you couldn't just pass `response.Body` to any func that accepts `io.Reader` as one would expect.

**Comment by imroc** [comment]
Yes, adding restore body is simple, and it will not affect performance, but it can reduce the read closed body caused by users not knowing the default auto read response.
