### ISSUE TITLE
get 请求带body时报错

### ISSUE THREAD

**Issue by seamusopen** [imroc/req#153]
使用:
          client := req.C()
          resp, err := client.R().
		          SetBodyJsonMarshal(xxxx).
		          SetResult(&xxxx).
		          EnableDump().
		          Get(reqUrl)
错误:
          Get "http://xxx/": http: Request.ContentLength=477 with nil Body

**Comment by imroc** [comment]
多谢反馈，这是因为默认不允许GET请求带body，这里没判断好，应直接返回直观的错误提示。
启用GET带body的方法:
```go
client.EnableAllowGetMethodPayload()
```

不过这里我想考虑改成默认允许GET带body，避免有些用户有这种需求，但又没仔细看文档，导致请求过不去；当设置不允许时，带body返回有明确提示的error

**Comment by imroc** [comment]
暂时没有，我后面考虑建一个

**Comment by imroc** [comment]
这个小改进目前已经release到最新版

**Comment by imroc** [comment]
@seamusopen 已创建slack和qq交流群

## Contact

If you have questions, feel free to reach out to us in the following ways:

* [Github Discussion](https://github.com/imroc/req/discussions)
* [Slack](https://imroc-req.slack.com/archives/C03UFPGSNC8) (International) | [Join](https://slack.req.cool/)
* QQ Group (Chinese): 621411351 - <a href="https://qm.qq.com/cgi-bin/qm/qr?k=P8vOMuNytG-hhtPlgijwW6orJV765OAO&jump_from=webapi"><img src="https://pub.idqqimg.com/wpa/images/group.png"></a>
