### ISSUE TITLE
如何关闭client或者request？ dial tcp: lookup www.baidu.com on 172.29.4.52:53: dial udp 172.xxx.xxx.2:53: socket: too many open files

### ISSUE THREAD

**Issue by SummerSec** [imroc/req#155]
如何关闭client或者request？

**Comment by SummerSec** [comment]
Get "http://baidu.com/api/api.json": dial tcp: lookup baidu.com  on 172.29.4.52:53: dial udp 172.29.4.52:53: socket: too many open files

**Comment by imroc** [comment]
请求结束会自动close。
这个报错是进程 open file 达到数量上限（包括连接)，可以先用lsof看下这个进程打开了哪些fd，找到进程pid，然后:
```bash
lsof 2>/dev/null | grep $PID
```

也看下进程的 fd 上限:

```bash
cat /proc/$PID/limits | grep 'open files'
```

统计下大部分占用的都是些什么

**Comment by imroc** [comment]
正好今天启用了qq交流群，可以加下

## Contact

If you have questions, feel free to reach out to us in the following ways:

* [Github Discussion](https://github.com/imroc/req/discussions)
* [Slack](https://imroc-req.slack.com/archives/C03UFPGSNC8) (International) | [Join](https://slack.req.cool/)
* QQ Group (Chinese): 621411351 - <a href="https://qm.qq.com/cgi-bin/qm/qr?k=P8vOMuNytG-hhtPlgijwW6orJV765OAO&jump_from=webapi"><img src="https://pub.idqqimg.com/wpa/images/group.png"></a>

**Comment by imroc** [comment]
比较常见的原因是，没优化ulimit配置，默认每个进程的 max open files 只有 1024，并发一高很容易出现这种报错

**Comment by SummerSec** [comment]
> 比较常见的原因是，没优化ulimit配置，默认每个进程的 max open files 只有 1024，并发一高很容易出现这种报错

谢谢，是的，修改一下ulimit就行了。
