### ISSUE TITLE
V3 文件上传 出现异常 但使用http直接发送则正常  错误: An existing connection was forcibly closed by the remote host.

### ISSUE THREAD

**Issue by 23233** [imroc/req#160]
版本 `V3.20.1` 
使用 `http` Post 一切正常
```
	bodyBuffer := &bytes.Buffer{}
	bodyWriter := multipart.NewWriter(bodyBuffer)

	fileWriter, _ := bodyWriter.CreateFormFile("media", fileName)
	file, _ := os.Open(imgPath)
	defer file.Close()
	io.Copy(fileWriter, file)

	contentType := bodyWriter.FormDataContentType()
	bodyWriter.Close()

	resp, err := http.Post(uri, contentType, bodyBuffer)
	defer resp.Body.Close()

```

使用 `req` 请求 报错 
```
Transfer-Encoding: chunked
Content-Type: multipart/form-data; boundary=395f49fda9a7eca4bb9fc629fda87bdc280ae3519f904b6082da55cf47a8
Accept-Encoding: gzip

HTTP/1.1 412 Precondition Failed
Connection: keep-alive
Date: Sat, 27-Aug-2022 03:04:36 GMT
Content-Length: 0 <----- 这里就异常
write tcp 192.168.1.121:59013->183.2.143.222:443: wsasend: An existing connection was forcibly closed by the remote host.
```

```
	c := req.C()
	c.SetTimeout(20 * time.Second)
	resp, err := c.R().SetFile("media", imgPath).Post(uri)
```
![image](https://user-images.githubusercontent.com/12870070/187011714-a78590d1-f13b-4e84-a18d-3e95fc358f35.png)
![image](https://user-images.githubusercontent.com/12870070/187011723-9593a254-7248-4257-9ba8-f56129e5fce0.png)

**Comment by imroc** [comment]
看接口是微信公众号的，具体是哪个？有文档吗，我测试下

**Comment by 23233** [comment]
@imroc  这个  `https://developers.weixin.qq.com/miniprogram/dev/framework/security.imgSecCheck.html` 微信的内容安全接口

**Comment by imroc** [comment]
嗯，看到了。已经进行了对比，看起来应该是server端期望上传的文件大小是可预知的，需要指明Content-Length

<img width="1403" alt="图片" src="https://user-images.githubusercontent.com/7448852/187018045-e95e65ce-0068-4eb3-8ed9-209a3dd1ddbb.png">

req 上传时默认用的 chunked 方式。我这边验证下，如果是这个问题，默认不用 chunked，提供可选项，对大文件上传可用 chunked

**Comment by imroc** [comment]
最新版已经默认不使用 chunked encoding 方式上传了，已验证微信接口成功，这是前后版本效果对比
<img width="1400" alt="图片" src="https://user-images.githubusercontent.com/7448852/187021169-fb015a51-8319-451c-ae56-d2005ed2e635.png">

Request 支持了 `EnableForceChunkedEncoding` 和 `DisableForceChunkedEncoding`，在一般在上传大文件，和需要设置文件上传回调函数时强制使用 chunked encoding

**Comment by 23233** [comment]
nice 可以了 感谢! @imroc
