### ISSUE TITLE
Meaning of   FirstResponseTime  and  ResponseTime ？

### ISSUE THREAD

**Issue by bryant-rh** [imroc/req#161]
Meaning of   FirstResponseTime  and  ResponseTime ？

FirstResponseTime: is a duration that server took to respond first byte since.
// connection ready (after tls handshake if it's tls and not a reused connection)

ResponseTime:      is a duration since first response byte from server to

What is the difference between the two？

**Comment by imroc** [comment]
1) dns lookup --> 2) tcp connect --> 3) tls handshake --> 4) server respond first byte --> 5) server response complete

* `FirstResponseTime` is 3-->4
* `ResponseTime` is 4-->5
