### ISSUE TITLE
大量访问，是否会造成内存泄露？

### ISSUE THREAD

**Issue by Xwudao** [imroc/req#162]
半个小时就500多MB，直觉告诉我不应该这么多：

![image](https://user-images.githubusercontent.com/31327868/189625090-108a07cc-dd41-4596-bc30-f62854ce389e.png)

看内存是io.ReadAll （String()方法）造成的：

![image](https://user-images.githubusercontent.com/31327868/189624467-cc97a38b-8f9e-4c90-9382-b8bf3869d087.png)

但是按理说，用完之后，应该会被gc回收呀。

![image](https://user-images.githubusercontent.com/31327868/189624647-a7c76c2c-c986-4c87-b665-106dc81b1041.png)

---

目前，我的情况是同一个client，会复用（会用同一个client请求n次），会不会是上次的body内容没有释放？

然后，这个程序大概有10来个client

**Comment by imroc** [comment]
默认情况下，req默认读取body(可通过`client.DisableAutoReadResponse()`禁用)，存到Response结构体的内部body字段，通常resp用完就丢了，指针没继续被引用，会被golang自动gc释放掉)

**Comment by imroc** [comment]
只要指针释放了就会自动gc掉，通过写简单程序就可以进行验证。

可以看看业务代码中，resp指针有没有哪里被引用了没释放，或body有没有被哪里单独引用过没释放。

**Comment by Xwudao** [comment]
@imroc 感谢回复。

大概我的流程如下：

```go

type Data struct {
	http    *req.Client
	proxies []string
}

func NewData(proxies []string) *Data {
	b := &Data{
		http:    req.NewClient().SetUserAgent(mobileUA).SetTimeout(time.Second * 10),
		proxies: proxies,
	}

	return b
}

func (b *Data) search(q string) ([]string, error) {
	var (
		all    = 20
		offset = 0
		links  []string
		api    = "https://xxxx/search"
	)
	for offset < all {
		query := map[string]string{
			"q": q,
		}
		proxy := utils.ChooseOne(b.proxies)

		resp, err := b.http.SetProxyURL(proxy).R().SetQueryParams(query).Get(api)
		if err != nil {
			return nil, err
		}

		html := resp.String()

		doc, err := goquery.NewDocumentFromReader(strings.NewReader(html))
		if err != nil {
			return nil, err
		}

		doc.Find("a[_ctf='rdr_T']").Each(func(idx int, selection *goquery.Selection) {
			href, _ := selection.Attr("href")
			l := utils.FindAbsUrl(utils.RemoveExtraSpace(href))
			if l != "" {
				links = append(links, l)
			}
		})
		offset += 10
	}

	return links, nil
}

```

不应该有泄露呀？

我是没看出来

**Comment by Xwudao** [comment]
直接返回resp.String()不会造成吧：

```go
func (v *VisitHelper) GetHtml(u string) (string, error) {
	resp, err := v.http.R().Get(u)
	if err != nil {
		return "", err
	}
	return resp.String(), nil
}
```

**Comment by imroc** [comment]
不会。可以用 pprof 生成 svg，看下调用关系和内存

**Comment by imroc** [comment]
或者是不是并发量较大，虽然会被gc，但也不是立即gc

**Comment by Xwudao** [comment]
> 或者是不是并发量较大，虽然会被gc，但也不是立即gc

我也怀疑是并发量的问题，昨天晚上到了1200MB，但好像也不是无限制增长。应该是和req无关。

谢谢您！
