### ISSUE TITLE
Request error stream error 

### ISSUE THREAD

**Issue by omerfruk** [imroc/req#163]
hi, I have a site that I request a lot. I use this package lots but ı naver see this error. the code is running then it gives this error for 5 or 6 requests if i stop and run it again it does the same thing. Can you help me ? 

> Post "https://b2b.otoismail.com.tr/Arama/UrunArama": stream error: stream ID 47; ENHANCE_YOUR_CALM; received from peerResults:  500
> Post "https://b2b.otoismail.com.tr/Arama/UrunArama": stream error: stream ID 49; ENHANCE_YOUR_CALM; received from peerResults:  1000
> Post "https://b2b.otoismail.com.tr/Arama/UrunArama": stream error: stream ID 51; ENHANCE_YOUR_CALM; received from peerResults:  1500
> Post "https://b2b.otoismail.com.tr/Arama/UrunArama": stream error: stream ID 53; ENHANCE_YOUR_CALM; received from peerResults:  2000
> Post "https://b2b.otoismail.com.tr/Arama/UrunArama": stream error: stream ID 55; ENHANCE_YOUR_CALM; received from peerResults:  2237

errors like this

**Comment by imroc** [comment]
`ENHANCE_YOUR_CALM (0xb):  The endpoint detected that its peer is exhibiting a behavior that might be generating excessive load.` (see [http2 error code](https://httpwg.org/specs/rfc7540.html#ErrorCodes))

Server responded with an `ENHANCE_YOUR_CALM` frame, it seems that the server thinks that the client sends too many requests. In other words, you are rate limited.
