### ISSUE TITLE
Add query parameters with string slice

### ISSUE THREAD

**Issue by Fimeo** [imroc/req#164]
Hello,

Thanks for this amazing tool, I suggest an improvement concerning the construction of query parameters with a new function AddQueryParams(key string, values []string) which adds a new entry of the key for each value of the slice.
This avoids a for loop in each implementation to add it in the construction of the url by the function.

Have a nice day

**Comment by imroc** [comment]
Release in v3.23.0

**Comment by Fimeo** [comment]
Works great ! Thanks
