### ISSUE TITLE
Use custom http client and or transport

### ISSUE THREAD

**Issue by DAlperin** [imroc/req#166]
I have a custom transport that I currently use like this:

```go
func (t *Tunnel) NewHttpClient() Client {
	net.DefaultResolver = t.resolv
	underlyingTransport := &http.Transport{
		DialContext: t.net.DialContext,
	}
	transport := Transport{
		token:               t.State.Token,
		underlyingTransport: underlyingTransport,
	}

	return Client{HttpClient: http.Client{Transport: &transport}}
}
```

Is there a way to use this transport with `req` like I do with `http.Client`?

**Comment by imroc** [comment]
Some advanced capabilities of req depend on the Transport implemented by req itself, such as dump, debug, http3, etc. If you customize your own transport implementation, these advanced capabilities will not be available.

Here's how to customize the transport:
```go
client := req.C()

client.GetClient().Transport = transport
```

What needs do you want to achieve? Maybe you don't need to customize the transport, req itself provides a lot of customization options:

```go
client := req.C()
client.SetDial(t.net.DialContext)
client.SetCommonBearerAuthToken(t.State.Token)
```

**Comment by DAlperin** [comment]
Ahah! SetDial is exactly what I need I think. Thank you!
