### ISSUE TITLE
unexpected EOF 报错

### ISSUE THREAD

**Issue by Schira4396** [imroc/req#172]
resp,err := req.R().Get("https://xx)
如上，在获取响应时出现了unexpected EOF的报错，挂burp或者fiddler抓包可以发现响应是正常的，但是读取并处理的时候出了问题？
![image](https://user-images.githubusercontent.com/57404930/195000709-f2181da4-868a-4085-b7c0-912036970f3d.png)
响应如图，看起来没毛病啊？
而且神奇的是我挂了代理，就能成功读取响应，无代理的情况下就会爆这个错

**Comment by imroc** [comment]
具体是什么url？复现代码可以发下吗

**Comment by Schira4396** [comment]
> 具体是什么url？复现代码可以发下吗

url的话，这个站点我搭在本地的，站点是vcenter，就是vmware那个虚拟化平台

代码：
`
client := req.C()
client.EnableForceHTTP1()
// client.DisableAutoReadResponse()
client.EnableInsecureSkipVerify()
client.SetTimeout(4 * time.Second)
resp, err := client.R().
		SetHeaders(myheader).
		Get(url + "/websso/SAML2/SSO/vsphere.local?SAMLRequest=")
res = resp.String()
`

我如果不管这个报错，那么resp就是空的，管这个报错就是unexpected EOF，代理是burpsuite。响应就是图中那个
我尝试过直接用io读body也直接是空的

**Comment by imroc** [comment]
不要代理，调试下看
```go
req.C().DevMode().EnableInsecureSkipVerify().SetHeaders(myheader).MustGet("url + "/websso/SAML2/SSO/vsphere.local?SAMLRequest=")
```

**Comment by Schira4396** [comment]
> ```go
> req.C().DevMode().EnableInsecureSkipVerify().R().SetHeaders(myheader).MustGet("url + "/websso/SAML2/SSO/vsphere.local?SAMLRequest=")
> ```

![image](https://user-images.githubusercontent.com/57404930/195004906-b129c107-cca7-4be0-86db-7ff2b5927718.png)
如图，看起来是获取到了响应的，但是还是报了一个unexpected EOF

**Comment by Schira4396** [comment]
> 

@imroc

**Comment by imroc** [comment]
像是 server 本身响应有点不正常，你可以用标准库试试

**Comment by Schira4396** [comment]
> 像是 server 本身响应有点不正常，你可以用标准库试试

那这个问题能解决不师傅

**Comment by Schira4396** [comment]
> 像是 server 本身响应有点不正常，你可以用标准库试试

或者我在哪可以捕获到响应末尾的这个报错

**Comment by imroc** [comment]
> 或者我在哪可以捕获到响应末尾的这个报错

```go
client := req.R().DisableAutoReadResponse().EnableForceHTTP1().EnableInsecureSkipVerify()

resp, err := client.Get(url)

...


body, err := resp.ToString()

if err == io.ErrUnexpectedEOF && body != "" {
    // 有EOF报错但body有内容（可能没读完整server端就断开了）
}
```

**Comment by imroc** [comment]
彻底解决得修复服务端，看截图是一直响应重复行，到中途就直接断开了

**Comment by Schira4396** [comment]
> ```go
> req.R().DisableAutoReadResponse().EnableForceHTTP1().EnableInsecureSkipVerify()
> ```

你这段第一句就错了……

**Comment by imroc** [comment]
> > ```go
> > req.R().DisableAutoReadResponse().EnableForceHTTP1().EnableInsecureSkipVerify()
> > ```
> 
> 你这段第一句就错了……

微调下：
```go
client := req.C().DisableAutoReadResponse().EnableForceHTTP1().EnableInsecureSkipVerify()

resp, err := client.R().Get(url)

...


body, err := resp.ToString()

if err == io.ErrUnexpectedEOF && body != "" {
    // 有EOF报错但body有内容（可能没读完整server端就断开了）
}
```

**Comment by Schira4396** [comment]
> ```go
> if err == io.ErrUnexpectedEOF && body != "" {
>     // 有EOF报错但body有内容（可能没读完整server端就断开了）
> }
> ```



> 

实测这样写的话输出的响应是空的，，我刚刚尝试了用http标准库，好家伙直接报runtime error: invalid memory address or nil pointer dereference

**Comment by imroc** [comment]
> 实测这样写的话输出的响应是空的
我看了下，ToString() 如果有 error，body 就返回空了，刚已经优化了下，可以升级到最新，即使有error，如果有读取部分body内容，也会返回

**Comment by imroc** [comment]
之前代码还可以简化成：
```go
client := req.C().EnableForceHTTP1().EnableInsecureSkipVerify()

resp, err := client.R().Get(url)

if err == io.ErrUnexpectedEOF && resp.String() != "" {
    // 有EOF报错但body有内容（可能没读完整server端就断开了）
}
```

**Comment by Schira4396** [comment]
> Reference

好的感谢
