### ISSUE TITLE
remove the judgment condition of IsSuccess when parsing the response body

### ISSUE THREAD

**Issue by hansedong** [imroc/req#173]
I am using `req` in my project, and `req` is a library that is very convenient to use. However, I have a problem: when the server side returns http status code as 400, `req` will not parse the response body.

There is a prerequisite for req to parse the response body, that is, the returned status code must be success( 199 < http status code < 300 ). The code is as follows:

```go
func parseResponseBody(c *Client, r *Response) (err error) {
	if r.Response == nil || r.StatusCode == http.StatusNoContent {
		return
	}
	if r.Request.Result != nil && r.IsSuccess() {
		err = unmarshalBody(c, r, r.Request.Result)
		if err == nil {
			r.result = r.Request.Result
		}
	}
	...
}
```

In some scenarios, when the server returns a 400 status code, it also returns the content of the response body, and I need to parse its content.

So, I would like to ask, is this `IsSuccess` condition necessary, and can we consider removing it?

**Comment by imroc** [comment]
Usually 4xx is an error response, to automatically unmarshal the error response you can SetError:
```go
client.R().SetResult(&successResult).SetError(&errorResult).Get(url)
```

**Comment by imroc** [comment]
checkout https://req.cool/docs/tutorial/handle-response/#unmarshal-response-body

**Comment by hansedong** [comment]
> Usually 4xx is an error response, in general, the response format is different from the normal response, to automatically unmarshal the error response you can SetError:
> 
> ```go
> resp, err := client.R().SetResult(&successResult).SetError(&errorResult).Get(url)
> ...
> if resp.IsSuccess() {
>     // read successResult
> } else if resp.IsError() {
>     // read errorResult
> }
> ```

Thanks for your reply, it has been solved perfectly by the above suggestion.
