### ISSUE TITLE
Automatic Parallel Download for Range Requests

### ISSUE THREAD

**Issue by darthShadow** [imroc/req#177]
Hi,

Love the project and am currently using it as an embedded transport in my custom roundtripper. I have a feature enhancement that I am not sure is possible but figured I would ask anyway.

Would it be possible to automatically split a request (in the roundtrip function) into multiple requests for parallel downloading if there is a range header present? The response bodies could probably then be appended into the resultant response body of the last received response.

Calling the explicit parallel download function will require significant changes in my implementation, which I would like to avoid if at all possible.

Thanks for the consideration.

**Comment by imroc** [comment]
Parallel download is already supported: https://req.cool/docs/tutorial/download/#parallel-download

**Comment by darthShadow** [comment]
Sorry, I didn't explain my needs clearly. I am aware of the parallel download functionality but there are 2 issues with using it:

* It supports only downloading to file and doesn't support returning a response object with the Body filled with the downloaded bytes
* Even if the above is addressed, it will require significant changes in my project to differentiate between file downloads vs. regular requests

Hope that makes my problem clear now.

I was hoping for a way to just create a request with the appropriate range header set and the `req` transport could automatically split it up into parallel requests with sub-chunks of the requested range which are then combined into a response body before returning the response object.

**Comment by imroc** [comment]
This is not appropriate, if you want to get the total response bytes, you can download it to bytes.Buffer instead of file:
```go
	client := req.C()
	buf := &bytes.Buffer{}
	client.NewParallelDownload(url).SetOutput(buf).Do()
	body := buf.Bytes()
```

**Comment by imroc** [comment]
Nop, cuz it actually has multiple response, merging into one does not conform to the semantics of response

**Comment by darthShadow** [comment]
Understood, thanks for the help.
