### ISSUE TITLE
cannot determine the unmarshal function

### ISSUE THREAD

**Issue by n0v3xx** [imroc/req#179]
Hi,
i got such debug messages in my log:
2022/10/17 23:29:41.891031 DEBUG [req] cannot determine the unmarshal function with "text/plain;charset=UTF-8" Content-Type, default to json

There is no way to set a default content type for the response or?

But i dont enable debug or dumping. Looks like a bug.

**Comment by imroc** [comment]
Upgrade to latest version and try again?

**Comment by n0v3xx** [comment]
Thanks it works, i had the 3.22.
