### ISSUE TITLE
Support http.Request.Close

### ISSUE THREAD

**Issue by zema1** [imroc/req#183]
In some case, I need to close the underlying connection after a request is done. In go stardard http package, we can use request.Close to do that.

```
r := http.NewRequest()
r.Close = true
```

I hope that in this method can be implemented, thanks.

**Comment by imroc** [comment]
It has just been implemented, you can update to the latest version, and then use it like this:
```go
client.R().EnableCloseConnection().Get(url)
```

**Comment by imroc** [comment]
In addition, you can also use a separate client for short connection requests:
```go
client := req.C().DisableKeepAlives()
```

**Comment by zema1** [comment]
Great job! Thanks!
