### ISSUE TITLE
Why disableAutoReadResponse is false by default?

### ISSUE THREAD

**Issue by hoslo** [imroc/req#184]
when i proxy download file
1. 
```golang
router.GET("/download/buffer", func(c *gin.Context) {

		buf := &bytes.Buffer{}
		ctx := context.Background()
		resp, err := req.DefaultClient().R().SetContext(ctx).SetOutput(buf).Get("http://localhost:8888/2.jpg")
		if err != nil || resp.GetStatusCode() != http.StatusOK {
		         // other code ...
			c.Status(http.StatusInternalServerError)
			return
		}

		io.Copy(c.Writer, buf)

	})
```

is slower than 
```golang
router.GET("/download", func(c *gin.Context) {
		req.DefaultClient().DisableAutoReadResponse()

		ctx := context.Background()
		resp, err := req.DefaultClient().R().SetContext(ctx).Get("http://localhost:8888/2.jpg")
		if err != nil || resp.GetStatusCode() != http.StatusOK {
		         // other code ...
			c.Status(http.StatusInternalServerError)
			return
		}

		io.Copy(c.Writer, resp.Body)

	})
```

**Comment by imroc** [comment]
> Why disableAutoReadResponse is false by default? 

It is convenient to dump the complete content without reading the response manually when dump is enabled. 


When `SetOutput` is called, the response body will not be read automatically into memory even if disableAutoReadResponse is false, and finally it will be downloaded directly by `io.Copy`. In theory, the above two methods should be similar. Repeat the test several times to see if there is any noticeable difference.

**Comment by hoslo** [comment]
> > Why disableAutoReadResponse is false by default?
> 
> It is convenient to dump the complete content without reading the response manually when dump is enabled.
> 
> When `SetOutput` is called, the response body will not be read automatically into memory even if disableAutoReadResponse is false, and finally it will be downloaded directly by `io.Copy`. In theory, the above two methods should be similar. Repeat the test several times to see if there is any noticeable difference.

Yes, you are right, there is no noticeable difference in their efficiency, but DownloadBuffer uses more memory, how to reduce memory usage?
```golang
goos: linux
goarch: amd64
pkg: go_test
cpu: Intel(R) Core(TM) i3-10100 CPU @ 3.60GHz
BenchmarkDownloadBuffer-8            183         133622081 ns/op        268444121 B/op       105 allocs/op
BenchmarkDownload-8                  199         121235285 ns/op           40235 B/op         81 allocs/op
PASS
ok      go_test 70.735s
```

**Comment by imroc** [comment]
Use `SetOutput(c.Writer)`

**Comment by imroc** [comment]
Download to writer directly, no need to do additional copy.

**Comment by hoslo** [comment]
> Download to writer directly, no need to do additional copy.

But if the status code is 404, Use SetOutput(c.Writer) will still return a 200 status code

**Comment by imroc** [comment]
> But if the status code is 404, Use SetOutput(c.Writer) will still return a 200 status code

Then use `DisableAutoReadResponse()` and `io.Copy` is the best option.

**Comment by hoslo** [comment]
> > But if the status code is 404, Use SetOutput(c.Writer) will still return a 200 status code
> 
> Then use `DisableAutoReadResponse()` and `io.Copy` is the best option.

DisableAutoReadResponse can only be used on the client side, so I think whether DisableAutoReadResponse should be added in the request

And I have one more question
```shell
TotalTime         : 6.671208207s
FirstResponseTime : 9.321713ms
ResponseTime      : 20.308µs
IsConnReused:     : true
RemoteAddr        : 10.23.254.60:80
```
in this case, what will cause TotalTime to be so much larger than FirstResponseTime+ResponseTime

**Comment by imroc** [comment]
You can use another client if you don't want all request DisableAutoReadResponse

**Comment by imroc** [comment]
> And I have one more question
> 
> ```shell
> TotalTime         : 6.671208207s
> FirstResponseTime : 9.321713ms
> ResponseTime      : 20.308µs
> IsConnReused:     : true
> RemoteAddr        : 10.23.254.60:80
> ```
> 
> in this case, what will cause TotalTime to be so much larger than FirstResponseTime+ResponseTime

Cost too much time sending request, only 9.3ms reading response.

**Comment by hoslo** [comment]
> > And I have one more question
> > ```shell
> > TotalTime         : 6.671208207s
> > FirstResponseTime : 9.321713ms
> > ResponseTime      : 20.308µs
> > IsConnReused:     : true
> > RemoteAddr        : 10.23.254.60:80
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > in this case, what will cause TotalTime to be so much larger than FirstResponseTime+ResponseTime
> 
> Cost too much time sending request, only 9.3ms reading response.

too much time sending request？which cost?

**Comment by imroc** [comment]
No, I said it wrong, this is a reused connection request, `FirstResponseTime` including start from sending request to first byte returned by the server, `ResponseTime` is the duration that reading response. TotalTime so much larger than FirstResponseTime+ResponseTime is not expected, can you write the reproducible code? (Publicly accessible tests)

**Comment by hoslo** [comment]
> No, I said it wrong, this is a reused connection request, `FirstResponseTime` including start from sending request to first byte returned by the server, `ResponseTime` is the duration that reading response. TotalTime so much larger than FirstResponseTime+ResponseTime is not expected, can you write the reproducible code? (Publicly accessible tests)

basicly like this
```golang
	uRfileClinet = reqm.NewClient()
	uRfileClinet.GetTransport().SetMaxIdleConns(500)
	uRfileClinet.GetTransport().SetMaxConnsPerHost(500)
	uRfileClinet.GetTransport().SetIdleConnTimeout(90 * time.Second)
	uRfileClinet.DisableAutoReadResponse()
	
	resp, err := uRfileClinet.R().
				EnableTrace().
				SetContext(context.Background()).
				SetHeader("Authorization", signature("GET", ufile_svc.BucketName, fileName, ufile_svc.PrivateKey, ufile_svc.PublicKey, "")).
				Get(url)
				
	//ufile related function
func signature(method string, bucket string, key string, private string, public string, content_type string) string {
	hmacHandle := hmac.New(sha1.New, []byte(private))
	//sigData = method + "\n" + md5 + "\n" + contentType + "\n" + date + "\n"
	signString := strings.ToUpper(method) + "\n\n" + content_type + "\n\n/" + bucket + "/" + key
	hmacHandle.Write([]byte(signString))
	return "UCloud " + public + ":" + base64.StdEncoding.EncodeToString(hmacHandle.Sum(nil))
}			
```

**Comment by hoslo** [comment]
> No, I said it wrong, this is a reused connection request, `FirstResponseTime` including start from sending request to first byte returned by the server, `ResponseTime` is the duration that reading response. TotalTime so much larger than FirstResponseTime+ResponseTime is not expected, can you write the reproducible code? (Publicly accessible tests)

I also found that case
```golang
trace: 
TotalTime         : 31.946665277s
DNSLookupTime     : 27.816927ms
TCPConnectTime    : 31.891081167s
TLSHandshakeTime  : 0s
FirstResponseTime : 27.722239ms
ResponseTime      : 22.592µs
IsConnReused:     : false
RemoteAddr        : 10.23.255.247:80
```

**Comment by imroc** [comment]
> > No, I said it wrong, this is a reused connection request, `FirstResponseTime` including start from sending request to first byte returned by the server, `ResponseTime` is the duration that reading response. TotalTime so much larger than FirstResponseTime+ResponseTime is not expected, can you write the reproducible code? (Publicly accessible tests)
> 
> basicly like this
> 
> ```go
> 	uRfileClinet = reqm.NewClient()
> 	uRfileClinet.GetTransport().SetMaxIdleConns(500)
> 	uRfileClinet.GetTransport().SetMaxConnsPerHost(500)
> 	uRfileClinet.GetTransport().SetIdleConnTimeout(90 * time.Second)
> 	uRfileClinet.DisableAutoReadResponse()
> 	
> 	resp, err := uRfileClinet.R().
> 				EnableTrace().
> 				SetContext(context.Background()).
> 				SetHeader("Authorization", signature("GET", ufile_svc.BucketName, fileName, ufile_svc.PrivateKey, ufile_svc.PublicKey, "")).
> 				Get(url)
> 				
> 	//ufile related function
> func signature(method string, bucket string, key string, private string, public string, content_type string) string {
> 	hmacHandle := hmac.New(sha1.New, []byte(private))
> 	//sigData = method + "\n" + md5 + "\n" + contentType + "\n" + date + "\n"
> 	signString := strings.ToUpper(method) + "\n\n" + content_type + "\n\n/" + bucket + "/" + key
> 	hmacHandle.Write([]byte(signString))
> 	return "UCloud " + public + ":" + base64.StdEncoding.EncodeToString(hmacHandle.Sum(nil))
> }			
> ```

Not reproduced yet

**Comment by imroc** [comment]
> 

It seems that it takes too long to establish a tcp connection

**Comment by imroc** [comment]
> > No, I said it wrong, this is a reused connection request, `FirstResponseTime` including start from sending request to first byte returned by the server, `ResponseTime` is the duration that reading response. TotalTime so much larger than FirstResponseTime+ResponseTime is not expected, can you write the reproducible code? (Publicly accessible tests)
> 
> I also found that case
> 
> ```go
> trace: 
> TotalTime         : 31.946665277s
> DNSLookupTime     : 27.816927ms
> TCPConnectTime    : 31.891081167s
> TLSHandshakeTime  : 0s
> FirstResponseTime : 27.722239ms
> ResponseTime      : 22.592µs
> IsConnReused:     : false
> RemoteAddr        : 10.23.255.247:80
> ```

It seems that it takes too long to establish a tcp connection

**Comment by hoslo** [comment]
> > > No, I said it wrong, this is a reused connection request, `FirstResponseTime` including start from sending request to first byte returned by the server, `ResponseTime` is the duration that reading response. TotalTime so much larger than FirstResponseTime+ResponseTime is not expected, can you write the reproducible code? (Publicly accessible tests)
> > 
> > 
> > I also found that case
> > ```go
> > trace: 
> > TotalTime         : 31.946665277s
> > DNSLookupTime     : 27.816927ms
> > TCPConnectTime    : 31.891081167s
> > TLSHandshakeTime  : 0s
> > FirstResponseTime : 27.722239ms
> > ResponseTime      : 22.592µs
> > IsConnReused:     : false
> > RemoteAddr        : 10.23.255.247:80
> > ```
> 
> It seems that it takes too long to establish a tcp connection

after disableAutoReadResponse set
Should I close resp.Body? In the above case I did not close

**Comment by imroc** [comment]
> after disableAutoReadResponse set Should I close resp.Body? In the above case I did not close

If you DisableAutoReadResponse and read resp.Body manually, then you should close resp.Body by yourself.

And in this case, TraceInfo is currently inaccurate, because the duration to read the response body cannot be counted.

**Comment by hoslo** [comment]
> > after disableAutoReadResponse set Should I close resp.Body? In the above case I did not close
> 
> If you DisableAutoReadResponse and read resp.Body manually, then you should close resp.Body by yourself.
> 
> And in this case, TraceInfo is currently inaccurate, because the duration to read the response body cannot be counted.

ok, thank you
