### ISSUE TITLE
上传文件时，开启调试dump，如何隐藏打印大量二进制信息的问题

### ISSUE THREAD

**Issue by liaohongxing** [imroc/req#185]
开启 .DevMode() 模式时，屏幕被大量二进制信息淹没 。上面的 request  都看不到。能不能有个选项或者插件 。隐藏这些二进制信息。或者将 二进制信息 替换为 binary data 字符代替, 代表这里有二进制信息

**Comment by imroc** [comment]
```go
req.DevMode().EnableDumpAllWithoutRequestBody()
```
