### ISSUE TITLE
SetTimeout  Doesn't work

### ISSUE THREAD

**Issue by lingxiao00** [imroc/req#186]
Here's what I wrote。No matter how many settings，only wait 1minute。

resp, err := req.C().SetTimeout(5000*time.Second).SetTLSHandshakeTimeout(5000*time.Second).EnableInsecureSkipVerify().R().SetHeader("token", token).SetHeader("Content-Type", "application/json").SetBody(fbody).SetResult(&gbody).Post(url)

**Comment by imroc** [comment]
I think it's closed by server or other device between client and server, you can check it by capturing packets with  tcpdump

**Comment by lingxiao00** [comment]
感谢回复，应该不是这个原因。我试了下，如果设置5秒钟，是可以生效的，但设成大于1分钟的，就不行了，最多等待1分钟就断开了。我的服务端没有问题，我用前端网页是可以等待超过1分钟的。但使用这个包就不行。

**Comment by lingxiao00** [comment]
非常感谢，是我这儿的问题。
我在测试环境试了一下，timeout确实起作用了，生产环境不行。
区别就是测试环境服务端是在本地服务器上直接部署的，生产环境服务端是在阿里云的k8s上部署的。目前怀疑是k8s的ingress配置可能有问题。我再继续排查。
感谢！！！！！

**Comment by imroc** [comment]
猜测是ingress网关这里的默认超时为1min，可以给阿里云提单确认，调整配置
