### ISSUE TITLE
Adding a query parameter in the request middleware doesn't work

### ISSUE THREAD

**Issue by eugene-manuilov** [imroc/req#190]
Hello,

I try to add a dynamic query parameter in the request middleware, but unfortunately it doesn't seem to work, I don't see it's being added to the request URL when the debug log is enabled. Am i doing something wrong or it is impossible?

```go
c := req.NewClient()
c.OnBeforeRequest(func(client *req.Client, req *req.Request) error {
    req.SetQueryParam("timestamp", strconv.FormatInt(time.Now().UnixMilli(), 10))
    return nil
})
c.EnableDebugLog().Get("https://example.com/").Do()
```

**Comment by imroc** [comment]
It's because user-defined middleware is executed before internal middleware, you can upgrade to the latest version, the order has been adjusted.

**Comment by eugene-manuilov** [comment]
Yes, it works now! Thanks! 🎉
