### ISSUE TITLE
How to set connect timeout

### ISSUE THREAD

**Issue by iyaozhen** [imroc/req#194]
> The timeout includes connection time, any redirects, and reading the response body.

But, connect timeout is useful throw network error quickly. Especially complex network environment.

**Comment by imroc** [comment]
You can customize the dial function:
```go
	client := req.C().SetDial(func(ctx context.Context, network, addr string) (net.Conn, error) {
		dialer := net.Dialer{
			Timeout: 3 * time.Second,
		}
		return dialer.Dial(network, addr)
	})

```
