### ISSUE TITLE
Stay up to date with the Golang source code

### ISSUE THREAD

**Issue by nclv** [imroc/req#199]
[http2/transport.go](https://github.com/imroc/req/blob/master/internal/http2/transport.go) should be updated following the updates of https://go.googlesource.com/net/+/master/http2/transport.go.

See the [logs](https://go.googlesource.com/net/+log/master/http2/transport.go) and [a bug fix that could be merged](https://go.googlesource.com/net/+/f486391704dcfa95dab69d779cb1574e3c1f7db1).

**Comment by imroc** [comment]
This is on the schedule, I'll do it later in spare time

**Comment by imroc** [comment]
Now it's stay up to date, you can upgrade to latest version.
