### ISSUE TITLE
[Question] 是否支持请求后的中间件？？？

### ISSUE THREAD

**Issue by shuqingzai** [imroc/req#202]
只看到可以配置请求前中间件和响应后中间件，但是请求后可能没有响应，那似乎不会触发中间件，如：请求一个 不存在或不能响应（有可能服务端URL已经过期）的 URL ，客户端请求就会出错，这种情况如何处理？？？

**Comment by imroc** [comment]
可以更新到最新版，优化了下逻辑，即便发生error（比如server一直不响应直至超时），也会执行响应中间件，有error会记录在 resp.Err 中，有需要可以在中间件内判断

**Comment by shuqingzai** [comment]
req 版本
```text
v3.29.0
```

![image](https://user-images.githubusercontent.com/44406033/211967284-71675d7c-5a20-47ea-b9ea-50a9f13296f4.png)

请求一个不存在的URL时，错误并没有 `resp.Response` 结构体，这种只能自己判断吗？是否有更好的方式？比如有一个统一的错误判断？现在是需要先判断 `err != io.EOF` 和 `resp.Response != nil` 才能读取响应体，否则就会空指针

**Comment by imroc** [comment]
只要 resp.Err 为 nil，resp.Response 就不为 nil。
通常判断下 if resp.Err != nil，记录或打印错误就return。后面的就可以放心读取resp.Response的字段了，官网有示例 https://req.cool/docs/tutorial/middleware-for-request-and-response/#response-middleware

**Comment by shuqingzai** [comment]
> 只要 resp.Err 为 nil，resp.Response 就不为 nil。 通常判断下 if resp.Err != nil，记录或打印错误就return。后面的就可以放心读取resp.Response的字段了，官网有示例 https://req.cool/docs/tutorial/middleware-for-request-and-response/#response-middleware

我也是按文档写的，但是有错误时，一般需要知道是客户端错误（如：httpStatus 400 - 499）还是服务端错误（如：httpStatus 500+），方便排查问题吧

**Comment by imroc** [comment]
都有 status 返回了，说明正常响应了就不算error，resp.Err 应该都为 nil 了吧，一般只有网络错误、unmarshal失败这种error才会记录到 resp.Err

**Comment by shuqingzai** [comment]
> 都有 status 返回了，说明正常响应了就不算error，resp.Err 应该都为 nil 了吧，一般只有网络错误、unmarshal失败这种error才会记录到 resp.Err

服务端有响应，但是 statusCode 不是 200~299 不是认为错误吗？这种应该在 `error` 体现吧

**Comment by shuqingzai** [comment]
> req 版本
> 
> ```
> v3.29.0
> ```
> 
> ![image](https://user-images.githubusercontent.com/44406033/211967284-71675d7c-5a20-47ea-b9ea-50a9f13296f4.png)
> 
> 请求一个不存在的URL时，错误并没有 `resp.Response` 结构体，这种只能自己判断吗？是否有更好的方式？比如有一个统一的错误判断？现在是需要先判断 `err != io.EOF` 和 `resp.Response != nil` 才能读取响应体，否则就会空指针

在 resp.Response == nil 时， `IsSuccess` 或 `IsError` 都是 false ，这应该是有歧义的吧？
https://github.com/imroc/req/blob/28436ebfcaea0dbc34c9b9c9caba66f502bc81e8/response.go#L30

https://github.com/imroc/req/blob/28436ebfcaea0dbc34c9b9c9caba66f502bc81e8/response.go#L38

**Comment by imroc** [comment]
两回事哈，IsSuccess 或 IsError 是判断的响应状态码，是成功响应还是错误响应，可以用于SetResult和SetError哪个被自动unmarshal了，这些前提都是没有error发生。

error是记录子在resp.Err上。

是有点歧义，但没想到更好的方式

**Comment by ifooth** [comment]
可否加一个`OnError`中间件，专门处理错误请求的`(r *req.Request, err error)`

**Comment by imroc** [comment]
> 可否加一个`OnError`中间件，专门处理错误请求的`(r *req.Request, err error)`

现有的Response中间件(OnAfterResponse)里可以直接判断是否有error，没必要再引入专门的error中间件 https://req.cool/docs/examples/handle-exceptions-with-middleware/
