### ISSUE TITLE
"Get \"https://xxxxx.com/xxxx/xxxxx\": remote error: tls: internal error",

### ISSUE THREAD

**Issue by WyntersN** [imroc/req#208]
报错 
`Req().R().SetResult(&result).SetHeader("accesstoken", token).Get("https://xxxxx.com/xxxx/xxxxx")`
"Get \"https://xxxxx.com/xxxx/xxxxx\": remote error: tls: internal error",

**Comment by imroc** [comment]
像是 server 端的 tls 不规范？有可复现的url么

**Comment by WyntersN** [comment]
Url：aHR0cHM6Ly9hcGkueWFuZ2tlZHVvLmNvbS91c2VyL3Nob3J0X3Byb2ZpbGUvbWU=

**Comment by imroc** [comment]
url base64 解码出来是：https://api.yangkeduo.com/user/short_profile/me

抓包可以看到，是tls握手时，server端响应的server hello里带的错误信息，需要检查server端
![image](https://user-images.githubusercontent.com/7448852/216900393-2cc31388-f3ee-42dc-b101-34df61936840.png)

**Comment by WyntersN** [comment]
那可以忽略掉这个握手错误，获取返回信息么

**Comment by imroc** [comment]
> 那可以忽略掉这个握手错误，获取返回信息么

目前不行，go标准库也一样。后续可以考虑加下这个忽略tls错误的功能

**Comment by WyntersN** [comment]
那哪个版本能更新上去，用API调试工具是 能直接获取到返回的JSON信息

**Comment by WyntersN** [comment]
我用go 标准库 访问它能正常获取到
![image](https://user-images.githubusercontent.com/27792650/216920003-95914f36-413c-489f-b90a-34c96212d6cb.png)

**Comment by WyntersN** [comment]
#244 已经解决
