### ISSUE TITLE
Is req.client() concurrently safe?

### ISSUE THREAD

**Issue by StellarisW** [imroc/req#211]
I was using a shared req.Client to send diffrent requests, but some how some requests will get same response, how to avoid it?
only using lock can I solve such a problem.

**Comment by StellarisW** [comment]
Here's my simplyfied scenario model

```go
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/imroc/req/v3"
	"net/http"
	"sync"
	"time"
)

const (
	baseUrl = "xxx.com/"
)

type Doc struct {
	Foo string `json:"foo"`
	Bar string `json:"bar"`
}

var (
	client *req.Client
)

func init() {
	client = req.NewClient().
		SetTimeout(3 * time.Minute).
		SetCommonRetryCount(5).
		SetCommonRetryFixedInterval(5 * time.Second)
}

func main() {
	wg := sync.WaitGroup{}

	requestIds := make([]string, 0, 20)
	insertedDocs := make([]interface{}, 0, 20)

	ctx := context.Background()
	for _, id := range requestIds {
		wg.Add(1)
		go func(cid string) {
			defer wg.Done()
			httpRes := client.Get(baseUrl + cid).Do(ctx)
			if httpRes == nil {
				return
			}
			if httpRes.GetStatusCode() != http.StatusOK {
				return
			}

			var doc Doc

			err := json.Unmarshal(httpRes.Bytes(), &doc)
			if err != nil {
				fmt.Println(err)
				return
			}

			insertedDocs = append(insertedDocs, doc)
		}(id)
	}

	wg.Wait()

	fmt.Println(insertedDocs)

	// There will be several identical documents in "insertedDocs"
}
```

Is this expected?

**Comment by StellarisW** [comment]
The previous model cannot be completely summarize the scenario, the following is the modified

```go
package main

import (
	"context"
	"github.com/PuerkitoBio/goquery"
	"github.com/imroc/req/v3"
	"go.uber.org/zap"
	"net/http"
	"sync"
	"time"
)

var (
	client *req.Client
)

func init() {
	client = req.NewClient().
		SetTimeout(3 * time.Minute).
		SetCommonRetryCount(5).
		SetCommonRetryFixedInterval(5 * time.Second).
		EnableDumpEachRequest()
}

var Logger = zap.NewExample()

var srcRequestIds = []string{
	"38563733816935586",
	"38563733816933566",
	"38563733816932708",
	"38563733816932456",
	"38563733816932202",
	"38563733816928868",
	"38563733816927564",
	"38563733816928008",
	"38563733816927234",
	"38563733816927127",
	"38563733816926709",
	"38563733816927005",
	"38563733816926598",
	"38563733816924042",
	"38563733816924440",
	"38563733816921261",
	"38563733816920533",
	"38563733816920567",
	"38563733816918804",
	"38563733816918196",
}

const (
	baseUrl = "http://xxx.cn"
)

func main() {
	ctx := context.Background()

	wg := sync.WaitGroup{}

	//_, _ = http.Get(baseUrl)
	_ = client.Get(baseUrl).Do(ctx)

	for i, id := range srcRequestIds {
		wg.Add(1)
		go func(ci int, cid string) {
			httpRes := client.Get(baseUrl + "/notify.do?method=oneNotify&notifyId=" + cid + "&type=1").Do(ctx)
			if httpRes == nil {
				Logger.Error("request http receive")
				return
			}
			if httpRes.GetStatusCode() != http.StatusOK {
				Logger.Error("request http status code", zap.String("status", httpRes.GetStatus()))
				return
			}
			doc, err := goquery.NewDocumentFromReader(httpRes.Body)
			if err != nil {
				Logger.Error("new doc from reader", zap.Error(err))
				return
			}

			title := doc.Find("div.content_title").Text()

			Logger.Debug("string ids", zap.Int("goroutine_id", ci), zap.String("news_id", cid), zap.String("title", title))
			wg.Done()
		}(i, id)
	}

	wg.Wait()

	return
}
```

Here you can see, **before** sending concurrent requests, I **have send** another request to baseurl,
and this will cause some concurrent requests will **get same response**, when I **change** `req.Client().Get().Do()` to `http.Get()`,
the same reponse will **not** be received, and this makes me so confused.

At present, it is known that this leads to the situation **that get same reponse**：
1. send a request to baseUrl and then send concurrent requests to the server on same baseUrl
2. send a request to baseUrl and then `time.Sleep(60*time.Second), then send concurrent requests to the server on same baseUrl

the situation **that will not get the same response**:
1.  use `http.Get` instead
2.  in goroutine we **use lock** to make sure that req.Client()  is serial processing
3. not send request using `req.Client().Get().Do()` before sending concurrent requests

As described above, I suppose it is not the **server-side** problem, but I'm not sure, what do you think?

**Comment by imroc** [comment]
Try not pass `ctx` to `Do` (not share context with all request).

**Comment by StellarisW** [comment]
all requests using `context.Background()` will get same reponse as well

**Comment by imroc** [comment]
That's weird, it would be nice if the url was publicly accessible so I could debug.
You can also dump the content yourself to see if you can find anything.

**Comment by StellarisW** [comment]
This url cannot be accessed through the internet.

so I try to use the request logic on `ZhiHu` but it is normal(weird...).

I'll inpect the requesting logic that sending requests to former baseUrl to see if  i can find anything.

**Comment by StellarisW** [comment]
I have figuerd it out, it is the server-side problem.
After I send the first request, I will get a sessionId in cookie,
then when I use client.ClearCookies() and then send concurrent requests and I will not get the same response anymore.

**Comment by imroc** [comment]
You can disable cookie by `client.SetCookieJar(nil)`

**Comment by StellarisW** [comment]
> You can disable cookie by `client.SetCookieJar(nil)`

many thanks ☺
