### ISSUE TITLE
SetUploadCallback without chunked encoding forced

### ISSUE THREAD

**Issue by Kirari04** [imroc/req#212]
so currently im uploading files to server like this:
```go
UploadFile, _ := os.Open("./files/1676820325866.mp4")
defer UploadFile.Close()
resp, err := Client.R().
  SetFileReader("file", "filename.mp4", UploadFile).
  SetFormData(map[string]string{
	  "api_key": c.ApiKey,
  }).
  SetUploadCallback(...).
  Post("https://external.service")
```

The problem is, when I use the upload with the `SetUploadCallback` method I get error 400 bad request.
```go
UploadFile, _ := os.Open("./files/1676820325866.mp4")
defer UploadFile.Close()
resp, err := Client.R().
  SetFileReader("file", "filename.mp4", UploadFile).
  SetFormData(map[string]string{
	  "api_key": c.ApiKey,
  }).
  SetUploadCallback(...).
  Post("https://external.service")
```
Error Response
```html
<html>    
<head><title>400 Bad Request</title></head>
<body>
<center><h1>400 Bad Request</h1></center>  
2023/02/19 17:14:45 Error: 400 : <html>
<head><title>400 Bad Request</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

The I tried the same script with the method `DisableForceChunkedEncoding` in the end and the upload works now but I dont get any callbacks during the upload.
```go
UploadFile, _ := os.Open("./files/1676820325866.mp4")
defer UploadFile.Close()
resp, err := Client.R().
  SetFileReader("file", "filename.mp4", UploadFile).
  SetFormData(map[string]string{
	  "api_key": c.ApiKey,
  }).
  SetUploadCallback(...).
  DisableForceChunkedEncoding().
  Post("https://external.service")
```

**My final question is**: is it possible to use some SetUploadCallback like method to still get the callbacks without enabling chunked encoding?

**Comment by imroc** [comment]
By default, forceChunkedEncoding is not enabled.
The key point is that you use `SetFileReader` to upload, lost the file size information, so can only use the chunked encoding to upload. You can use SetFile or SetUpload to upload.

**Comment by Kirari04** [comment]
thx for qour quick response.
Will this approach load the whole file in to memory?

**Comment by imroc** [comment]
> use `SetFileReader` to upload, lost the file size information, so can only use the chunked encoding to upload. You can use SetFile or SetUpload to upload

No

**Comment by imroc** [comment]
> Will this approach load the whole file in to memory?

No, it will not
