### ISSUE TITLE
Throttle requests

### ISSUE THREAD

**Issue by Fimeo** [imroc/req#214]
I build an application using goroutines. Each goroutine launches a set of requests to an external service.

However, it seems that the external service is not handling the load well. I regularly get `net/http: request cancelled (Client.Timeout exceeded while awaiting headers)` errors with about ten simultaneous requests. I have set a timeout of 15 seconds at the client.

It also seems that the first request always takes longer, is this due to DNS resolution?

Also, during a timeout request, accessing the response.TotalTime().String() returns negative values such as: `-2562047h47m16.854775808s`

It could also be interesting to add a throttle system to limit the number of concurrent requests. Through a before request function this seems possible, but a native method might be handy.

Req is well received for running concurrent requests? Isn't the client dependent on the current requests? 

Thanks

**Comment by imroc** [comment]
> It also seems that the first request always takes longer, is this due to DNS resolution?

Both dns and server logic are possible.

>  during a timeout request, accessing the response.TotalTime().String() returns negative values

Thanks for the feedback, I have found that if the trace is not enabled and the response is not received, the call `resp.TotalTime()` will have a negative value, it has been fixed now, you can upgrade to the latest version.

> Req is well received for running concurrent requests? Isn't the client dependent on the current requests?

Yes, every request is sent and received separately without interfering with each other, you can test it with the standard `net/http`, it should have the same result.
