### ISSUE TITLE
功能请求: ja3指纹

### ISSUE THREAD

**Issue by Ecalose** [imroc/req#215]
在某些场景下会校验ja3指纹，不知道作者后续有无此方面的相关计划呢

**Comment by imroc** [comment]
最近暂时没时间研究这个，这跟tls指纹有关，思路应该就是利用 `client.SetDialTLS` 来自定义tls握手，一般需要结合其他库，你可以研究下

**Comment by Ecalose** [comment]
ok

**Comment by Nyx2022** [comment]
> ok

请问有研究出怎么自定义ja3吗，可以分享下吗

**Comment by Ecalose** [comment]
> > ok
> 
> 请问有研究出怎么自定义ja3吗，可以分享下吗

并没，改用其他的库了

**Comment by Nyx2022** [comment]
> > > ok
> > 
> > 
> > 请问有研究出怎么自定义ja3吗，可以分享下吗
> 
> 并没，改用其他的库了

用的哪个库呢

**Comment by imroc** [comment]
tls指纹已支持 https://req.cool/zh/docs/tutorial/tls-fingerprinting/
