### ISSUE TITLE
No way to set http2.Transport parameters

### ISSUE THREAD

**Issue by rohsaini** [imroc/req#216]
I'm looking forward to set StrictMaxConcurrentStreams, ReadIdleTimeout, PingTimeout, etc of https://pkg.go.dev/golang.org/x/net/http2 Transport struct. I see no api exposed as part of that.

**Comment by imroc** [comment]
Now you can upgrade to the latest version,  call client or transport's `SetHTT2XXX` to set http2-specific settings.

**Comment by rohsaini** [comment]
Thanks. I see some parameters are still missing, like TLSClientConfig, DisableCompression, CountError, etc.

**Comment by imroc** [comment]
TLSClientConfig is not http2-specific, you can directly use `client.SetTLSClientConfig`, which support all http version, and the same as `DisableCompression`.

And `CountError`is not exposed yet, do you really need it? if you want to record error, you can use `client.OnAfterResponse` to add response middleware (will be executed even request is failed) to record errors.

**Comment by rohsaini** [comment]
Sure. I'll see if no strict need of CountError and if OnAfterResponse solves my purpose. In case not, I'll open another ticket.
You can close this ticket for now. Thanks for providing the quick fixes.

**Comment by imroc** [comment]
hint: `resp.Err` is not nil if error occurs in ResponseMiddleware.
