### ISSUE TITLE
How to get the current URL (after redirect)

### ISSUE THREAD

**Issue by chuanhhoang** [imroc/req#219]
I am using req with automated redirecting but I couldn't find a way to find the current url (the redirected one). Is there any way to find it?

**Comment by imroc** [comment]
You can get raw redirected http.Request  from raw http.Response:
```go
	resp, err := req.R().Get("https://baidu.com")
	if err != nil {
		panic(err)
	}
	fmt.Println("redirected urll", resp.Response.Request.URL.String())
```

**Comment by chuanhhoang** [comment]
> You can get raw redirected http.Request from raw http.Response:
> 
> ```go
> 	resp, err := req.R().Get("https://baidu.com")
> 	if err != nil {
> 		panic(err)
> 	}
> 	fmt.Println("redirected url", resp.Response.Request.URL.String())
> ```

Thank you, it works.
