### ISSUE TITLE
can't work in golang version 1.20

### ISSUE THREAD

**Issue by cxytz01** [imroc/req#220]
# github.com/imroc/req/v3/internal/qtls
~/go/pkg/mod/github.com/imroc/req/v3@v3.25.0/internal/qtls/go120.go:6:13: cannot use "The version of quic-go you're using can't be built on Go 1.20 yet. For more details, please see https://github.com/lucas-clemente/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built on Go 1.20 yet. F...) as int value in variable declaration
# github.com/lucas-clemente/quic-go/internal/qtls

~/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.29.1/internal/qtls/go120.go:5:13: cannot use "The version of quic-go you're using can't be built on Go 1.20 yet. For more details, please see https://github.com/lucas-clemente/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built on Go 1.20 yet. F...) as int value in variable declaration (exit status 1)

**Comment by imroc** [comment]
please upgrade your req version
