### ISSUE TITLE
No status code received when having error

### ISSUE THREAD

**Issue by chuanhhoang** [imroc/req#221]
When making a request via proxy, sometime the password if wrong and then 407 status code is returned. But with imroc, while the error is "Proxy Authentication Required", the status is is 0 (Zero) when getting the original status code with GetStatusCode, which is incorrect.

**Comment by imroc** [comment]
The proxy logic is consistent with the standard library `net/http`, the `Response` represents the server-side response rather than the proxy response. If it is an error returned by the proxy, it is should be in the `error` variable.

**Comment by piercefreeman** [comment]
This underlying need was addressed in the net standard lib in https://github.com/golang/go/issues/54299. If you get req's active transport you can receive a more explicit callback and handle it like you do any other error.

```go
transport := client.GetTransport()

transport.OnProxyConnectResponse = func(ctx context.Context, proxyURL *url.URL, connectReq *http.Request, connectRes *http.Response) error {
    if connectRes.StatusCode != http.StatusOK {
        return fmt.Errorf("proxy error: status=%d body=%s",
            connectRes.StatusCode,
            connectRes.Status)
        }
    return nil
}
```
