### ISSUE TITLE
go版本1.20编译报错

### ISSUE THREAD

**Issue by nuo010** [imroc/req#224]
![image](https://user-images.githubusercontent.com/68454615/228404524-fcf0a26b-d706-40db-9b0f-d759727fb120.png)

错误内容

# github.com/lucas-clemente/quic-go/internal/qtls
C:\Users\Erin\go\pkg\mod\github.com\lucas-clemente\quic-go@v0.28.1\internal\qtls\go120.go:6:13: cannot use "The version of quic-go you're using can't be built on Go 1.20 yet. For more details, please see https://github.com/lucas-clemente/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built on Go 1.20 yet. F...) as int value in variable declaration
# github.com/imroc/req/v3/internal/qtls
C:\Users\Erin\go\pkg\mod\github.com\imroc\req\v3@v3.26.5\internal\qtls\go120.go:6:13: cannot use "The version of quic-go you're using can't be built on Go 1.20 yet. For more details, please see https://github.com/lucas-clemente/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built on Go 1.20 yet. F...) as int value in variable declaration

**Comment by imroc** [comment]
升级一下req版本
