### ISSUE TITLE
[BadDesign] Response的IsSuccessState()为false时，Err变量为nil

### ISSUE THREAD

**Issue by YiuTerran** [imroc/req#226]
我这里401时遇到这个问题，比较反直觉。

虽然也不是不行，但是感觉这算是一个坑…

**Comment by imroc** [comment]
没想到更好的设计，有建议么~

**Comment by YiuTerran** [comment]
简单点处理感觉可以把Status里面里面的字符串用`errors.New`生成一个错误，比如401就是`Unauthorized`。不过非标准的code，比如599之类的，可能只能用`Unknown`了。

**Comment by imroc** [comment]
这样 Err 不为 nil，但网络传输确是是正常的，很多时候应用层是希望根据不同状态码来执行不同的处理逻辑，大多数人的习惯是err不为nil就记录日志然后return了，后续处理逻辑就不执行了，更容易造成问题。

如果稍微认真看下当前的方法注释文档或示例，一般应该也不会掉坑~

**Comment by YiuTerran** [comment]
嗯，也可以。不过最好在代码里加一些注释。
