### ISSUE TITLE
`errRetryableWithUnReplayableBody` should only be thrown for requests with bodies (POST/PUT/DELETE)

### ISSUE THREAD

**Issue by abdusco** [imroc/req#228]
I was working on adding some common retry functionality for get requests to handle http2 `GOAWAY` frames. [Docs](https://req.cool/docs/tutorial/retry/) were quite helpful in that regard, thank you.

However once I played around with it, I kept getting `errRetryableWithUnReplayableBody` even for GET requests, regardless of it supports sending a request body or not.

The error is thrown here:

https://github.com/imroc/req/blob/7a7eada8c72d39f847158b6047a6d83dd42a631c/request.go#L542-L544

I feel like there should be another condition there, `r.methodSupportsBody()`.

**Comment by abdusco** [comment]
If this issue makes sense and I'm not overlooking something important, I can send a PR for it

**Comment by imroc** [comment]
`unReplayableBody` should be nil if `SetBody` is not been used, check your code to see if there is a call to `SetBody`.

**Comment by imroc** [comment]
Do you use `client.EnableAllowGetMethodPayload()`, and `SetBody` with `io.Reader` in GET requests?

**Comment by imroc** [comment]
If we want more rigorous, we should to add another condition: payload is allowed in current request method, that is, `!r.client.isPayloadForbid(r.Method)`

**Comment by abdusco** [comment]
> Do you use client.EnableAllowGetMethodPayload(), and SetBody with io.Reader in GET requests?

No, just regular GET requests.

> unReplayableBody should be nil if SetBody is not been used

I use it somewhere else, but instead of giving up outright, the check to throw the error should be done after the request is sent. 

My use-case: I'm writing a client for an API. It has various CRUD endpoints. I use keep-alives the connection is reused as expected. When polling an endpoint, the server closes the connection after some time, and I receive `Transport received Server's graceful shutdown GOAWAY` error from stdlib. 

I want to use retries here. If the request fails and can't be retried, it's OK to throw an error. But in our case I get the error even before request is sent.

**Comment by imroc** [comment]
Do you reuse `Request` object for different requests？

**Comment by abdusco** [comment]
OK, there has been some miscommunication on my part. The problem doesn't exist with GET requests. It's only with `SetBody`, and only when I give it an `io.Reader`. Understandably, you can't rewind the stream to resend the request, this makes sense.

However, if the req has unrewindable body, we don't perform the request at all, instead reject it with an error. 

I expected it to send the request, once it gets a response, check the retry conditions, then reject it, if needed.

Here's a test to show you what I mean:

```golang
// go.mod: github.com/imroc/req/v3 v3.33.2

package main

import (
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
	"time"

	"github.com/imroc/req/v3"
)

var client = req.NewClient().
	SetCommonRetryFixedInterval(time.Second * 2).
	SetCommonRetryCount(5).
	AddCommonRetryCondition(func(res *req.Response, err error) bool {
		return err != nil && strings.Contains(err.Error(), "GOAWAY")
	})

func TestErr(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte("ok"))
	}))
	defer server.Close()

	res, err := client.R().
		SetBody(strings.NewReader("a")).
		Put(server.URL)
	if err != nil {
		// fails here without sending the request
		t.Error(err)
	}
	if res.String() != "ok" {
		t.Error("request not sent")
	}
}

func TestWithoutRetry(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte("ok"))
	}))
	defer server.Close()

	res, err := client.R().
		SetBody(strings.NewReader("a")).
		// this is ok, because we opted out of retries
		SetRetryCount(0).
		Put(server.URL)
	if err != nil {
		t.Error(err)
	}
	if res.String() != "ok" {
		t.Error("request not sent")
	}
}

```

**Comment by abdusco** [comment]
While playing around with this, I realized that I could opt out of retries at the request level using `SetRetryCount` while still having a common retry policy. 

This is a good workaround for now. So if you think it's working as intended, feel free to close the issue.

**Comment by imroc** [comment]
This is intended, if you want enable retry, you should never use unrewindable body.
