### ISSUE TITLE
Incompatible with quic-go/quic-go@v0.34.0

### ISSUE THREAD

**Issue by gg718** [imroc/req#232]
One of my other dependencies pulled in a transient update of `quic-go/quic-go` from v0.33.0 to v0.34.0 and my code started to fail to compile with the following error:

> `github.com/imroc/req/v3@v3.33.2/internal/http3/client.go:269:37: c.conn.HandshakeComplete().Done undefined (type <-chan struct{} has no field or method Done)`

Would it be possible to fix this incompatibility?

**Comment by duzhipeng** [comment]
I have the same problem.

**Comment by imroc** [comment]
Try fix quic-go version to `v0.32.0` in `go.mod`?

**Comment by mih-kopylov** [comment]
`v0.33.0` also works fine, the issues only happen with `v0.34.0` that broke backward compatibility and changed `EarlyConnection` interface signature.
In `33` it was `HandshakeComplete() context.Context`
In `34` it became `HandshakeComplete() <-chan struct{}`

**Comment by shuqingzai** [comment]
> Try fix quic-go version to `v0.32.0` in `go.mod`?

有计划先修复这个吗？@imroc

**Comment by imroc** [comment]
> > Try fix quic-go version to `v0.32.0` in `go.mod`?
> 
> 有计划先修复这个吗？@imroc

req本身是依赖的这个版本，是需要自行改下自己项目`go.mod`中的quic-go版本

**Comment by shuqingzai** [comment]
> > > Try fix quic-go version to `v0.32.0` in `go.mod`?
> > 
> > 
> > 有计划先修复这个吗？@imroc
> 
> req本身是依赖的这个版本，是需要自行改下自己项目`go.mod`中的quic-go版本

是否应该升级一个版本来支持 `quic-go >= v0.34.0` 的版本？默认情况，下载的 `quic-go` 版本都是最新的版本，每个 req 使用者都需要手动更新 `go.mod` ，这不友好吧

**Comment by mih-kopylov** [comment]
It will also be broken if user does `go get -u ./...` to update dependencies. 
Effectively, the solution would be to add an exclusion to `go.mod` that looks like a temporary kludge.

I'd encourage the `req` library to be compilable with the latest version of `quic-go`.

**Comment by imroc** [comment]
If upgrade quic-go, it requires at least go1.19, if there is no better way, it will be aligned with the latest version of quic-go in the near future

**Comment by imroc** [comment]
Released in v3.34.0, now it requires go1.19, and support the latest quic-go

**Comment by gg718** [comment]
Working now, thanks!
