### ISSUE TITLE
WrapRoundTripFunc cause proxy not take effect

### ISSUE THREAD

**Issue by RonaldinhoL** [imroc/req#233]
```` golang
func main() {
	c := req.C()
	c.SetUserAgent("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36")

	c.GetTransport().WrapRoundTripFunc(func(rt http.RoundTripper) req.HttpRoundTripFunc {
		return func(req *http.Request) (resp *http.Response, err error) {
			return rt.RoundTrip(req)
		}
	})

	c = c.Clone().SetProxyURL("http://127.0.0.1:8888")
	resp, err := c.R().Get("https://www.baidu.com")

	fmt.Print(err)
	fmt.Print(resp.StatusCode)
}
````

**Comment by imroc** [comment]
Will figure it out when I'm free

**Comment by imroc** [comment]
The key point is `Clone()`. If you don’t clone, it can take effect. If you clone, it will not take effect due to the implementation of the transport middleware.

It may be a little difficult and it will take some time to solve this. I will think about it later when I have time. Before solving it, try to avoid cloning where middleware is used.

**Comment by RonaldinhoL** [comment]
so what is the best practice for changing proxy? should i clone new instance?

**Comment by imroc** [comment]
> so what is the best practice for changing proxy? should i clone new instance?

You can pre-create clients for each proxy, change the client when proxy needed to be changed.

**Comment by RonaldinhoL** [comment]
> The key point is `Clone()`. If you don’t clone, it can take effect. If you clone, it will not take effect due to the implementation of the transport middleware.
> 
> It may be a little difficult and it will take some time to solve this. I will think about it later when I have time. Before solving it, try to avoid cloning where middleware is used.

i think the transport middlewaret should be saved as req/resp callbacks instead of using closure

**Comment by imroc** [comment]
You can use callbacks with `client.OnBeforeRequest` and `client.OnAfterResponse`

**Comment by RonaldinhoL** [comment]
yeah i use transport middlewire for auto decompress br compressed body before, maybe Client.SetResponseBodyTransformer is a good choice for it

**Comment by imroc** [comment]
This is been fixed, both client middleware and transport middleware will work even after `Clone()`, will be released in the next version.
