### ISSUE TITLE
question: is there a way to use the content-disposition filename to download a file ?

### ISSUE THREAD

**Issue by sgaunet** [imroc/req#235]
Hello,

I would like to download a file from a server that I'm writting too. Here is the response http headers of the server:

```
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Disposition: attachment; filename="sample18.txt"
Content-Length: 2147479552
Content-Type: application/octet-stream
Last-Modified: Wed, 03 May 2023 13:15:28 GMT
Date: Wed, 03 May 2023 13:15:28 GMT
```

firefox download the file correctly with the name sample18.txt. How can I do with the req framework ?

Thanks

**Comment by imroc** [comment]
Currently there is no convenient way, you can use `client.DisableAutoReadResponse()` and parse response header `Content-Disposition`, get the filename, and then copy `resp.Body` to file with filename parsed by yourself.

**Comment by sgaunet** [comment]
Perfect, thank you, it's working
