### ISSUE TITLE
How to set Timeout for specify request and not affect global settings?

### ISSUE THREAD

**Issue by vikyd** [imroc/req#24]
How to set Timeout for specify request and not affect global settings?

**Comment by imroc** [comment]
sorry for the late reply, this is a example:
``` go
r := req.New()
r.SetTimeout(20 * time.Second)
resp, err := r.Get(url)
...
```

**Comment by vikyd** [comment]
https://github.com/imroc/req/blob/master/setting.go#L114

**Comment by imroc** [comment]
req.New() will new a http.Client, SetTimeout will apply a Timeout on that client, every request on that client will use the same Timeout, if you want to use another Timeout, just req.New() another client

**Comment by shuhrat-shokirov** [comment]
Hi, First of all I want to say thank you for such a wonderful package. I had one problem with the time out, I use what you indicated above, but the request still takes a long time

```r := req.New()
	r.SetTimeout(1*time.Second)

	resp, err := r.Post(url, header, req.BodyJSON(request))```

30.002710879s
