### ISSUE TITLE
Dump buffer is empty after request

### ISSUE THREAD

**Issue by flamedmg** [imroc/req#240]
Good morning!
I'm using one of the examples you provided here, but i also tried to examples from the website with no luck - can't get dump of the request/response. Here is how i'm doing that:
```
	responseData := &ShowClientResponse{}
	var reqBuf, respBuf bytes.Buffer
	dumpOpt := &req.DumpOptions{
		RequestHeader:  true,
		ResponseBody:   true,
		RequestBody:    true,
		ResponseHeader: true,
		Async:          true,
		RequestOutput:  &reqBuf,
		ResponseOutput: &respBuf,
	}

	httpReq := req.C().SetUserAgent("MyApi").SetTimeout(10*time.Second).R().SetDumpOptions(dumpOpt).EnableDump().SetHeader("Content-Type", "text/xml").SetContext(ctx).SetBodyXmlString(buf.String()).SetSuccessResult(responseData)
	resp, err := httpReq.Post(apiUrl)

	fmt.Println("request content:")
	fmt.Println(reqBuf.String())
	fmt.Println("response content:")
	fmt.Println(respBuf.String())
```
I'm getting empty request/response
I'm using latest req which is 3.35.0

Please advice!

**Comment by imroc** [comment]
Try set `Async` to `false` (which is default), if you print the dump buffer immediately when response received, At this time, the dump content may not be written into the specified buffer(cuz it's asynchronous).

**Comment by flamedmg** [comment]
I did it as you suggested with no luck. Still getting empty  dump, however if i set enable it on the client level i'm getting it to the stdout.

**Comment by imroc** [comment]
I tested that the setting at the request level is also ok, here is the sample code that works:
```go
package main

import (
	"bytes"
	"fmt"
	"github.com/imroc/req/v3"
)

func main() {
	var reqBuf, respBuf bytes.Buffer
	opt := &req.DumpOptions{
		RequestOutput:  &reqBuf,
		ResponseOutput: &respBuf,
		RequestHeader:  true,
		RequestBody:    true,
		ResponseHeader: true,
		ResponseBody:   true,
		Async:          false,
	}
	req.R().SetDumpOptions(opt).EnableDump().SetBody("test").MustPost("https://httpbin.org/post")

	fmt.Println("req:")
	fmt.Println(reqBuf.String())
	fmt.Println("resp:")
	fmt.Println(respBuf.String())
}

```

**Comment by flamedmg** [comment]
Your example works 100%. 
I found, that my code also works if i remove SetContext(ctx) from  the request. It looks like SetRequest somehow disturbs dumper that i see is bound to the context. It also works if i SetContext(ctx) before EnableDump()

**Comment by imroc** [comment]
It's because EnableDump saves request level dump options in context, if `SetContext(ctx)` after `EnableDump()`,  the context will override the context, and did not find a good way to merge two go contexts.

**Comment by imroc** [comment]
Added comments to `SetContext`:
```txt
// Attention: make sure call SetContext before EnableDumpXXX if you want to
// dump at the request level.
```
