### ISSUE TITLE
quic 0.35 compatibility

### ISSUE THREAD

**Issue by ice-cronus** [imroc/req#241]
I get compile errors when I upgrade github.com/quic-go/quic-go v0.34.0 => v0.35.0
```
github.com/imroc/req/v3/internal/http3
../../../../../../pkg/mod/github.com/imroc/req/v3@v3.35.0/internal/http3/client.go:45:21: undefined: quic.DialAddrEarlyContext
../../../../../../pkg/mod/github.com/imroc/req/v3@v3.35.0/internal/http3/roundtrip.go:23:23: undefined: quic.DialEarlyContext
```

Version is v3.35.0

**Comment by imroc** [comment]
Nice catch, quic-go `v0.35.0` is just released a few hours ago, which is slightly incompatible, it has been resolved now, the latest version of req has supported quic-go `v0.35.0`.
