### ISSUE TITLE
Get SSL 出错

### ISSUE THREAD

**Issue by WyntersN** [imroc/req#244]
提示报错：
Get "https://xxxxx.com": remote error: tls: internal error

这是为什么

**Comment by imroc** [comment]
看起来是tls握手时，server端响应了不规范的server hello

**Comment by WyntersN** [comment]
那怎么办，怎么解决

**Comment by imroc** [comment]
url可以公开访问么，我测试下

**Comment by WyntersN** [comment]
Get方式

URL：aHR0cHM6Ly9tb2JpbGUueWFuZ2tlZHVvLmNvbS9vcmRlcl9jaGVja291dC5odG1sP2dvb2RzX2lkPTQxNTkwNzgyNzgwJnNrdV9pZD00NjgyMDM3NDM5NzMmZ29vZHNfbnVtYmVyPTEmXz0yMzA2MTQwOTU5NDcyOTMxNDQ=

Header：Q29va2llOlBEREFjY2Vzc1Rva2VuPVFRTFZONk1OQk5WSkVSVkpUMktIQ0ZBWEZDVVpBQkhONFNBSENSUTRYN1JOT0ZLSkc2WFExMjIxZTVkClVzZXItQWdlbnQ6TW96aWxsYS81LjAgKGlQaG9uZTsgQ1BVIGlQaG9uZSBPUyAxNV81IGxpa2UgTWFjIE9TIFgpIEFwcGxlV2ViS2l0LzYwNS4xLjE1IChLSFRNTCwgbGlrZSBHZWNrbykgTW9iaWxlLzE1RTE0OCA9PT0gIGlPUy8xNS41IE1vZGVsL2lQaG9uZTE0LDUgQnVuZGxlSUQvY29tLnh1bm1lbmcucGluZHVvZHVvIEFwcFZlcnNpb24vNi4xNi4wIEFwcEJ1aWxkLzIwMjIwNjIyMjAyMiBwdmVyc2lvbi8yNDQ0IGNVUkwvNy43NS4w

**Comment by imroc** [comment]
抓包看tls握手包，go client发出client hello后，server端直接响应fatal error：
![image](https://github.com/imroc/req/assets/7448852/965ec3ce-8d51-4988-b2fa-9a7e44f2f3ed)

看起来是server端校验了tls指纹，识别到是go标准库的tls握手直接响应fatal error，不给访问。

解决方法：借助utls库来伪造tls握手指纹

代码示例：

```go
package main

import (
	"context"
	"crypto/tls"
	"github.com/imroc/req/v3"
	utls "github.com/refraction-networking/utls"
	"net"
	"strings"
)

var urlStr = "https://mobile.yangkeduo.com/order_checkout.html?goods_id=41590782780&sku_id=468203743973&goods_number=1&_=230614095947293144"

type TLSConn struct {
	*utls.UConn
}

func (conn *TLSConn) ConnectionState() tls.ConnectionState {
	cs := conn.Conn.ConnectionState()
	return tls.ConnectionState{
		Version:                     cs.Version,
		HandshakeComplete:           cs.HandshakeComplete,
		DidResume:                   cs.DidResume,
		CipherSuite:                 cs.CipherSuite,
		NegotiatedProtocol:          cs.NegotiatedProtocol,
		NegotiatedProtocolIsMutual:  cs.NegotiatedProtocolIsMutual,
		ServerName:                  cs.ServerName,
		PeerCertificates:            cs.PeerCertificates,
		VerifiedChains:              cs.VerifiedChains,
		SignedCertificateTimestamps: cs.SignedCertificateTimestamps,
		OCSPResponse:                cs.OCSPResponse,
		TLSUnique:                   cs.TLSUnique,
	}
}

func main() {
	c := req.C().DevMode()
	c.SetDialTLS(func(ctx context.Context, network, addr string) (net.Conn, error) {
		plainConn, err := net.Dial(network, addr)
		if err != nil {
			return nil, err
		}
		colonPos := strings.LastIndex(addr, ":")
		if colonPos == -1 {
			colonPos = len(addr)
		}
		hostname := addr[:colonPos]
		utlsConfig := &utls.Config{ServerName: hostname, NextProtos: c.GetTLSClientConfig().NextProtos}
		conn := utls.UClient(plainConn, utlsConfig, utls.HelloFirefox_Auto)
		return &TLSConn{conn}, nil
	})
	c.R().MustGet(urlStr)
}
```

**Comment by imroc** [comment]
#239  看来tls指纹伪装需求场景不少，打算内置到req中

**Comment by WyntersN** [comment]
十分感谢，我已测试通过

**Comment by Nyx2022** [comment]
> 

下个版本内置吗？

**Comment by imroc** [comment]
> > 
> 
> 下个版本内置吗？

嗯，而且稍后就会发版

**Comment by WyntersN** [comment]
> > > 
> > 
> > 
> > 下个版本内置吗？
> 
> 嗯，而且稍后就会发版

等会发版的时候 别忘了提供一下例子

**Comment by imroc** [comment]
> 等会发版的时候 别忘了提供一下例子

@WyntersN 已发布，更新就可以用：https://req.cool/docs/tutorial/tls-fingerprinting/

**Comment by Nyx2022** [comment]
> > 等会发版的时候 别忘了提供一下例子
> 
> @WyntersN 已发布，更新就可以用：https://req.cool/docs/tutorial/tls-fingerprinting/

https://req.cool/docs/tutorial/tls-fingerprinting/的注意：目前当设置了 tls 指纹，代理将不生效（如有设置）

这个是本身的代理协议和tls指纹有冲突，还是req在集成utls这个库的时候有些冲突呢

**Comment by imroc** [comment]
> 这个是本身的代理协议和tls指纹有冲突，还是req在集成utls这个库的时候有些冲突呢

原理是会调 SetDialTLS 覆盖 tls 建连握手的函数，也就会覆盖代理了，标准库也是这样，自定义了 DialTLS 函数，代理就不会生效: https://github.com/golang/go/blob/release-branch.go1.20/src/net/http/transport.go#L150-L151

> dial function for creating TLS connections for `non-proxied` HTTPS requests.

**Comment by imroc** [comment]
@Nyx2022 现在设置tls指纹后，即便设置了代理也可以生效了。底层不再调用`SetDialTLS`覆盖Transport的`DialTLSContext`，而是给Client新增了`SetTLSHandshake`函数来基于已有conn自定义tls握手操作。刚刚已发布，可以更新到最新版使用。
