### ISSUE TITLE
访问一个网站报错

### ISSUE THREAD

**Issue by Nyx2022** [imroc/req#245]
为访问一个网站htttps://xx.xx.xx.xx，但是报错：x509: cannot validate certificate for xx.xx.xx.xx because it doesn't contain any IP SANs。这是什么bug还是配置问题呢

**Comment by imroc** [comment]
看报错应该是用https访问了一个ip（非域名），而网站的证书是签发的域名，所以校验失败。
解决办法：
1. 使用签发的域名访问
2. 用 client.EnableInsecureSkipVerify() 忽略证书校验

**Comment by Nyx2022** [comment]
> 

确实是访问的ip，没法访问域名访问。我也一直启用了EnableInsecureSkipVerify()的，但是还是有上面那个错误。我感觉是自签名证书比较老了，但实际上在浏览器中是可以访问的

**Comment by imroc** [comment]
地址可以公开访问吗？我试下
