### ISSUE TITLE
Should I close the response body?

### ISSUE THREAD

**Issue by karelbilek** [imroc/req#247]
should I close response.Body when using imroc.req?

I need to read binary data with imroc.req. I am using the returned `res.Body` with `io.ReadAll`, but I am not sure if I should or should not close the response.Body.

And what if I don't read the response at all? Should I still close the response.Body? Or does req magically does that for me?

**Comment by karelbilek** [comment]
Ah nevermind it gets auto-read

**Comment by imroc** [comment]
Close response body manually is only needed when you [DisableAutoReadResponse](https://pkg.go.dev/github.com/imroc/req/v3#Client.DisableAutoReadResponse).
