### ISSUE TITLE
QUIC向上兼容版本

### ISSUE THREAD

**Issue by dollarkillerx** [imroc/req#249]
# github.com/quic-go/quic-go/internal/qtls
../../gopath/pkg/mod/github.com/quic-go/quic-go@v0.35.1/internal/qtls/go_oldversion.go:5:13: cannot use "The version of quic-go you're using can't be built using outdated Go versions. For more details, please see https://github.com/quic-go/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built using outdated Go...) as int value in variable declaration
note: module requires Go 1.19

go version: 1.20

**Comment by imroc** [comment]
看下相关依赖是不是更新到最新了，比如 github.com/quic-go/qtls-go1-20，确保是 v0.2.2 而不是 v.0.3.0。quic-go 自身依赖最近有 breaking change

**Comment by ManuelReschke** [comment]
I have also the problem with quic :(
ISSUE: https://github.com/quic-go/quic-go/issues/3933

What is the solution? Can you please answer in english. Thanks

**Comment by imroc** [comment]
> I have also the problem with quic :( ISSUE: [quic-go/quic-go#3933](https://github.com/quic-go/quic-go/issues/3933)
> 
> What is the solution? Can you please answer in english. Thanks

If your `quic-go` version is below `v0.36.1`, make sure your `github.com/quic-go/qtls-go1-20` is fixed to `v0.2.2` in `go.mod`

**Comment by cos800** [comment]
> 看下相关依赖是不是更新到最新了，比如 github.com/quic-go/qtls-go1-20，确保是 v0.2.2 而不是 v0.3.0。quic-go 自身依赖最近有 breaking change

看到go.mod文件里
```
github.com/quic-go/qtls-go1-20 v0.3.0 // indirect
```
确实是v0.3.0
需要怎么处理？

**Comment by imroc** [comment]
> 确实是v0.3.0 需要怎么处理？

先改成 v0.2.2 然后 go mod tidy 一下

我看最近quic-go最新版的依赖已经对齐到 v0.3.0了，预计不久后req这里也会跟进，之后 go get -u 也不会有问题了
