### ISSUE TITLE
Support header sort customization

### ISSUE THREAD

**Issue by imroc** [imroc/req#257]

**Comment by imroc** [comment]
ref: https://github.com/imroc/req/discussions/198#discussioncomment-6461365

**Comment by fedosgad** [comment]
You may want to take a look at https://github.com/fedosgad/oohttp/commits?author=fedosgad (disclaimer: it's my port of https://github.com/useflyent/fhttp patches) - this is exactly what you want to do.

**Comment by imroc** [comment]
Supported in the latest release: https://github.com/imroc/req/releases/tag/v3.39.0
