### ISSUE TITLE
[建议]默认的TLS 指纹功能不能越过cf的反爬虫

### ISSUE THREAD

**Issue by g-mero** [imroc/req#259]
尝试通过req库来代理chatgpt的web端，即使使用了tls指纹来伪装成浏览器发送请求还是会被cf拦截。

没办法，使用了(tls-client)[https://github.com/bogdanfinn/tls-client]这个库越过了，这个库好像是对utls进行了一些修改。

req是我用过最舒服的一个go的请求库了，项目里现在有几个请求库搞得我有点强迫症了，希望可以升级一下默认的tsl指纹功能。

**Comment by imroc** [comment]
能给个链接我测试下吗？最近正在HTTP指纹方面做一些能力增强，昨天刚发了调整http header顺序来伪造指纹的能力 https://github.com/imroc/req/releases/tag/v3.39.0

**Comment by imroc** [comment]
我试了用utls+一些header顺序控制，也能绕过cf反爬虫的网站，`tls-client` 这个库的README中的demo，其实也是利用了header控制+tls指纹一起协同来实现绕过的。

以下是我用req现有的能力实现绕过的实例：
```go
package main

import (
	"github.com/imroc/req/v3"
)

func main() {
	req.DevMode()
	req.SetCommonHeaders(map[string]string{
		"accept":          "*/*",
		"accept-language": "de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7",
		"user-agent":      "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36",
	}).SetCommonHeaderOrder(
		"accept",
		"accept-language",
		"user-agent",
	).SetTLSFingerprintChrome().SetCommonPseudoHeaderOder(
		":method",
		":authority",
		":scheme",
		":path",
	)
	req.MustGet("https://support.mexc.com/hc/zh-cn/sections/360000679912-%E6%9C%80%E6%96%B0%E5%85%AC%E5%91%8A")
}
```
> 注意示例中的网站在国内不能直接访问，需要代理

**Comment by imroc** [comment]
可以试试main函数中只保留第一行和最后一行（取消指纹相关设置），此时可以看到返回的页面没绕过cf反爬虫时的页面内容

**Comment by imroc** [comment]
计划再支持更多的指纹自定义，然后提供方便的封装，调用一下就能轻松全面模拟各种浏览器的指纹，即便最强反爬虫也不怕

**Comment by g-mero** [comment]
> 我试了用utls+一些header顺序控制，也能绕过cf反爬虫的网站，`tls-client` 这个库的README中的demo，其实也是利用了header控制+tls指纹一起协同来实现绕过的。
> 
> 以下是我用req现有的能力实现绕过cf的示例：
> 
> ```go
> package main
> 
> import (
> 	"github.com/imroc/req/v3"
> )
> 
> func main() {
> 	req.DevMode()
> 	req.SetCommonHeaders(map[string]string{
> 		"accept":          "*/*",
> 		"accept-language": "de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7",
> 		"user-agent":      "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36",
> 	}).SetCommonHeaderOrder(
> 		"accept",
> 		"accept-language",
> 		"user-agent",
> 	).SetTLSFingerprintChrome().SetCommonPseudoHeaderOder(
> 		":method",
> 		":authority",
> 		":scheme",
> 		":path",
> 	)
> 	req.MustGet("https://support.mexc.com/hc/zh-cn/sections/360000679912-%E6%9C%80%E6%96%B0%E5%85%AC%E5%91%8A")
> }
> ```
> 
> > 注意示例中的网站在国内不能直接访问，需要代理

谢谢，更新最新版本后使用您这段命令成功绕过了，期待以后的更新
