### ISSUE TITLE
Client.clone()有些属性没有复制

### ISSUE THREAD

**Issue by Nyx2022** [imroc/req#260]
我简单看了一下代码，req.Client.Clone()里面的逻辑有些属性是没有复制的，比如client.setDialTLS之后的DialContext好像就没有复制到CLone之后的客户端，望修复一下此类问题，谢谢

**Comment by imroc** [comment]
是有复制的，比如 `client.SetDialTLS` 设置的函数，最终是设置到 Transport 里的，Client 在 Clone的时候也会Clone Transport，Transport 里的 Options也会Clone

**Comment by Nyx2022** [comment]
好的，谢谢
