### ISSUE TITLE
怎么获得待跳转的URL

### ISSUE THREAD

**Issue by Xwudao** [imroc/req#264]
相关issue: https://github.com/imroc/req/issues/219

但是上面的解决办法是会访问到跳转后的地址，

我的目的是不访问，仅仅获取将要跳转的地址

**Comment by imroc** [comment]
禁止跳转然后获取header中的Location就行

`client.SetRedirectPolicy(req.NoRedirectPolicy())`

**Comment by Xwudao** [comment]
> 禁止跳转然后获取header中的Location就行
> 
> `client.SetRedirectPolicy(req.NoRedirectPolicy())`

多谢！
