### ISSUE TITLE
代理错误

### ISSUE THREAD

**Issue by Nyx2022** [imroc/req#266]
对于某一个全新的URL（之前没有在当前计算机中请求的），在使用代理请求的时候，有时候会间歇性出现这个错误：proxyconnect tcp: dial tcp :0: connectex: The requested address is not valid in its context.。还请麻烦修复一下，感谢感谢

**Comment by imroc** [comment]
代理地址自身用的域名吗？看报错像是代理地址解析出来的ip有问题

**Comment by Nyx2022** [comment]
对，代理地址本身也是域名

**Comment by imroc** [comment]
代理是有很多么？地址是从代理池查的？如果是，复现时记录下代理地址，然后在程序所在环境手动发起代理地址的域名解析看看

**Comment by Nyx2022** [comment]
代理地址就一个（没有使用cdn），只是网络环境比较差，而且同一时间发起的请求比较多。而且有些反复访问了很多次的域名在中间都会出现 dial tcp: lookup xxxxx: no such host和tls handshake error的错误。建议考虑弄个dns解析缓存机制在里面

**Comment by imroc** [comment]
那就是dns解析失败了。引入dns缓存会有很多坑导致其它问题（比如jvm），如果网络环境差，dns解析可能失败，代理能直接用ip就不用域名，绕过dns解析。

**Comment by Nyx2022** [comment]
> 

代理我确实可以这么做，但是其他的一些常规的URL，我也没办法都固定为ip，所以建议还是考虑一下缓存机制，只是看有没有哪种方案能规避你说的jvm问题

**Comment by imroc** [comment]
未来计划支持自定义dns解析器，可以顺带实现一个又dns缓存功能的解析器
