### ISSUE TITLE
tls还是有问题

### ISSUE THREAD

**Issue by Nyx2022** [imroc/req#267]
我用的是windows系统，req 3.41.3+utls 1.4.3+golang 1.21.0，同时也测了req 3.40.1+utls 1.3.3+golang 1.20.7环境，在访问https的时候还是会出现握手失败的问题，感觉还是有问题（浏览器是可以正常打开的）
![image](https://github.com/imroc/req/assets/51039208/7a0d251a-cae5-48b6-909f-e73f43098f8d)
还请帮忙修复，谢谢

**Comment by imroc** [comment]
没什么有用的信息，补充详细点吧

**Comment by imroc** [comment]
已私聊
