### ISSUE TITLE
tls证书验证

### ISSUE THREAD

**Issue by Nyx2022** [imroc/req#268]
有个https网站，我已经调用了EnableInsecureSkipVerify()方法禁止验证证书，但是还是提示了以下错误
![image](https://github.com/imroc/req/assets/51039208/d4481331-59c7-452f-84fa-76e34efd092f)
我看这个应该也是证书验证没通过的意思，我不知道还需要设置什么才能湖绿这个验证

**Comment by imroc** [comment]
发个url看看

**Comment by Nyx2022** [comment]
不能发在这里，能提供的联系方式吗？比如微信号啥的

**Comment by imroc** [comment]
> 不能发在这里，能提供的联系方式吗？比如微信号啥的

id: `QQ245671051`

**Comment by imroc** [comment]
已修复并发布
