### ISSUE TITLE
How to cancel request?

### ISSUE THREAD

**Issue by vikyd** [imroc/req#27]
How to cancel request?

**Comment by imroc** [comment]
does not support before, but just support it right now after I saw this issue, it's easy:
``` go
ctx, cancel := context.WithCancel(context.Background())
go func(){
  ...
  cancel()
  ...
}()
req.Get(url, ctx)
```
see commit: https://github.com/imroc/req/commit/b355b6f6842fbda1bee879f2846cb79424cad4de
latest commit is tagged `v0.2.3`
