### ISSUE TITLE
connection error: COMPRESSION_ERROR

### ISSUE THREAD

**Issue by elpaxel** [imroc/req#275]
When I'm using "ImpersonateChrome" request fails with "connection error: COMPRESSION_ERROR".
Only on this url: https://httpbingo.org/anything
Without "ImpersonateChrome" request is working fine.

go 1.20
req 3.41.7

    package main
    
    import (
        "fmt"
        "log"
        
        "github.com/imroc/req/v3"
    )
    
    func main(){
        client := req.C().ImpersonateChrome()
        
        resp, err := client.R().Get("https://httpbingo.org/anything")
        
        if err != nil {
            log.Fatal(err)
        }
        
        fmt.Println(resp.String())
    }

**Comment by elpaxel** [comment]
ImpersonateChrome - COMPRESSION_ERROR
ImpersonateFirefox - COMPRESSION_ERROR
ImpersonateSafari - works

**Comment by imroc** [comment]
Nice catch! It's been fixed in the latest version, try it.

**Comment by elpaxel** [comment]
Yep. Now this url is working: https://httpbingo.org/anything
But this url: https://9gag.com gives "connection error: FLOW_CONTROL_ERROR"
But it is working fine in 3.41.7-3.41.8

**Comment by imroc** [comment]
That's wired, will take some time to deep dive.

**Comment by imroc** [comment]
@elpaxel `FLOW_CONTROL_ERROR` has been fixed in the latest version

**Comment by elpaxel** [comment]
Thank you. Now everything works.
