### ISSUE TITLE
如何post方式请求数组body体

### ISSUE THREAD

**Issue by herozzm** [imroc/req#283]
比如在post的时候，请求的formdata为数组或者混合data：
SetFormData方法仅支持map[string]string，比如要`application/x-www-form-urlencoded`方式发送以下data值，用什么方式最好？
```
k[]: v1
k[]: v2
k[]: v3
a[]: v4
a[]: v5
a[2]: v6
b: v7
c: v8
....
```

另外如果能将url参数格式的string自动转换成map[string]string就好了，因为在浏览器调试工具中查看源很方便
![image](https://github.com/imroc/req/assets/8332269/42f03054-0669-471c-ba53-a3d5b00360eb)  
![image](https://github.com/imroc/req/assets/8332269/5c09a756-fce8-463f-bd54-38d912a31493)  
显然后者复制粘贴来的快很多
比如：
```go
stringUrl := "current=1&rowCount=10&searchPhrase=&query_bulletintitle=&query_startTime......"
client.R().SetFormData(stringUrl)
```

**Comment by imroc** [comment]
1. `SetFormDataFromValues` 可以传入原始的 `url.Values`，即一个key多个value

2. 如果想把url参数转成body里的form表单，然后利用 SetFormDataFromValues 传入，示例：
```go
package main

import (
	"net/url"

	"github.com/imroc/req/v3"
)

func main() {
	client := req.C().DevMode()
	values, err := url.ParseQuery("current=1&rowCount=10&searchPhrase=&query_bulletintitle=")
	if err != nil {
		panic(err)
	}
	client.R().SetFormDataFromValues(values).MustPost("https://httpbin.org/post")
}
```

当然参数全都是复制的url参数，并且能保证是url 编码过的，那直接SetBody传入也可以，手动设置Content-Type为 application/x-www-form-urlencoded

**Comment by herozzm** [comment]
还是不行，参数如果是这样子的话，顺序会被打乱而且就算自我纠正还是不行，我测试的网址如下  
JetBrains家的ide自带http client，可以正常获取结果，但是换`req`的`SetFormDataFromValues`则不行
```
POST http://xjg.jxufe.edu.cn/api-ajax_list-1.html
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

ajax_type%5B%5D=79_news&ajax_type%5B%5D=177&ajax_type%5B%5D=79&ajax_type%5B%5D=news&ajax_type%5B%5D=Y-m-d&ajax_type%5B%5D=50&ajax_type%5B%5D=12&ajax_type%5B7%5D%5B%5D=is_top+DESC&ajax_type%5B7%5D%5B%5D=displayorder+DESC&ajax_type%5B7%5D%5B%5D=inputtime+DESC&ajax_type%5B%5D=&is_ds=1
```

浏览器中的form参数示意图：
![image](https://github.com/imroc/req/assets/8332269/b2091def-6ac3-43f9-9743-54b1ae65b84b)

**Comment by imroc** [comment]
如果还要保证顺序，那就直接自己拼接来构造body吧

**Comment by Xwudao** [comment]
我简单写了一个将query转换为map的工具(复制查看源中的数据)：

![image](https://github.com/imroc/req/assets/31327868/5632049a-aced-4cc2-8b97-a4c0788a4619)


https://jutool.dev/#/urlParam


![image](https://github.com/imroc/req/assets/31327868/b011f834-f47c-4a22-b206-a62cf0918310)

**Comment by Xwudao** [comment]
![image](https://github.com/imroc/req/assets/31327868/610a4072-ec38-4a4c-9fd7-01afa9c42c79)
