### ISSUE TITLE
如何设置随机HTTP指纹？

### ISSUE THREAD

**Issue by herozzm** [imroc/req#284]
固定一个指纹，很快就被ban了，需要能够足够的多的指纹，然后随机挑选使用

**Comment by imroc** [comment]
没有内置那么多指纹，构造指纹的基础函数都有，可以根据需要进行DIY实现自己需要的指纹，参考 ImersonateXXX 的实现，代码量不多
![image](https://github.com/imroc/req/assets/7448852/14c1c3f2-8cef-404d-8908-4a54e4880cd7)

如果服务端校验不严，甚至可以只改header，比如加每次加个随机的key和value，其它的不动
