### ISSUE TITLE
可以添加一个设置用以自动添加 Referer 头？

### ISSUE THREAD

**Issue by Xwudao** [imroc/req#286]
就是在`R()`级别下，访问多个网址时，这个URL header['Referer']头上添加上个URL

比如：`SetAutoReferer(true)`

**Comment by imroc** [comment]
直接在请求级别设置需要的Referer头就行了吧

**Comment by Xwudao** [comment]
> 直接在请求级别设置需要的Referer头就行了吧

我说错了，应该是在全局级别设置？

在每次`R()`请求时，利用上次的URL到Referer，免得每次手动设置？

**Comment by imroc** [comment]
如果一批不同的url需要共用同一个Referer，那它们共用同一个client，在client级别设置Referer头就行了

client.SetCommonHeader("Referer", "xxx")

**Comment by Xwudao** [comment]
> 如果一批不同的url需要共用同一个Referer，那它们共用同一个client，在client级别设置Referer头就行了
> 
> client.SetCommonHeader("Referer", "xxx")

不是共用同一个Referer，如下 ：

```
var r = req.NewClient()

//1.

r.R().Get("https://bb.com/1111")


//2. 
r.R().SetHeader("Referer","https://bb.com/1111").Get("https://bb.com/2222") <-这样

//3.
r.R().SetHeader("Referer","https://bb.com/2222").Get("https://bb.com/3333") <-这样

```

**Comment by imroc** [comment]
> 不是共用同一个Referer，如下 ：
> 
> ```
> var r = req.NewClient()
> 
> //1.
> 
> r.R().Get("https://bb.com/1111")
> 
> 
> //2. 
> r.R().SetHeader("Referer","https://bb.com/1111").Get("https://bb.com/2222") <-这样
> 
> //3.
> r.R().SetHeader("Referer","https://bb.com/2222").Get("https://bb.com/3333") <-这样
> ```

这个其实直接利用req的中间件能力就能完成，可运行的示例：

```go
package main

import (
	"github.com/imroc/req/v3"
)

func NewClient() *req.Client {
	client := req.C().DevMode()
	var lastURL string
	client.OnBeforeRequest(func(_ *req.Client, req *req.Request) error {
		if lastURL != "" {
			req.SetHeader("Referer", lastURL)
		}
		lastURL = req.RawURL
		return nil
	})
	return client
}

func main() {
	client := NewClient()
	client.R().MustGet("https://httpbin.org/get?test=1")
	client.R().MustGet("https://httpbin.org/get?test=2")
	client.R().MustGet("https://httpbin.org/get?test=3")
}

```

做到框架里的话，如果是并发请求，又要考虑到底取哪个作为上一次的url，如果中途需要暂停几个请求不加referer，又该如何等问题，所以先不考虑做到框架里，在业务层面和基于中间件能力DIY是最合适的

**Comment by Xwudao** [comment]
> > 不是共用同一个Referer，如下 ：
> > ```
> > var r = req.NewClient()
> > 
> > //1.
> > 
> > r.R().Get("https://bb.com/1111")
> > 
> > 
> > //2. 
> > r.R().SetHeader("Referer","https://bb.com/1111").Get("https://bb.com/2222") <-这样
> > 
> > //3.
> > r.R().SetHeader("Referer","https://bb.com/2222").Get("https://bb.com/3333") <-这样
> > ```
> 
> 这个其实直接利用req的中间件能力就能完成，可运行的示例：
> 
> ```go
> package main
> 
> import (
> 	"github.com/imroc/req/v3"
> )
> 
> func NewClient() *req.Client {
> 	client := req.C().DevMode()
> 	var lastURL string
> 	client.OnBeforeRequest(func(_ *req.Client, req *req.Request) error {
> 		if lastURL != "" {
> 			req.SetHeader("Referer", lastURL)
> 		}
> 		lastURL = req.RawURL
> 		return nil
> 	})
> 	return client
> }
> 
> func main() {
> 	client := NewClient()
> 	client.R().MustGet("https://httpbin.org/get?test=1")
> 	client.R().MustGet("https://httpbin.org/get?test=2")
> 	client.R().MustGet("https://httpbin.org/get?test=3")
> }
> ```
> 
> 做到框架里的话，如果是并发请求，又要考虑到底取哪个作为上一次的url，如果中途需要暂停几个请求不加referer，又该如何等问题，所以先不考虑做到框架里，在业务层面和基于中间件能力DIY是最合适的

第一次了解中间件👍，多谢
