### ISSUE TITLE
Build Error: cannot use setDataFromSessionState

### ISSUE THREAD

**Issue by zdt1013** [imroc/req#298]
# github.com/quic-go/quic-go/internal/qtls
..\..\go\pkg\mod\github.com\quic-go\quic-go@v0.39.1\internal\qtls\go120.go:58:31: cannot use setDataFromSessionState (variable of type func([]byte)) as func([]byte) (allowEarlyData bool) value in struct literal (exit status 1)

go version go1.20.10 windows/amd64
req version: v3.42.1

go 1.19版本也试过报同样的错误

**Comment by imroc** [comment]
最新版不支持 go1.19，至少 1.20.

quic-go 版本指定 req 依赖的版本 0.38.1 试试
