### ISSUE TITLE
大佬，我看了一下文档没有找到支持websocket相关的

### ISSUE THREAD

**Issue by shuyabin** [imroc/req#301]
大佬我看了一下文档没有找到websocket链接的地方，咱们后续会支持波 或者有我没找到的隐藏用法？

**Comment by imroc** [comment]
暂不支持哈，未来不确定，也许会支持

**Comment by gospider007** [comment]
> 大佬我看了一下文档没有找到websocket链接的地方，咱们后续会支持波 或者有我没找到的隐藏用法？

this can help you: https://github.com/gospider007/requests/blob/master/test/protocol/websocket_test.go
