### ISSUE TITLE
proxy enhancement?

### ISSUE THREAD

**Issue by seaguest** [imroc/req#31]
Hello,

Is the http/https proxy authentication in plan?

will socks5 proxy be supported?

it would be nice if cookiejar could be supported.

best regards

**Comment by imroc** [comment]
proxy auth is just add a header, you can do it like this:
``` go
package main

import (
	"encoding/base64"
	"fmt"
	"github.com/imroc/req"
	"net/http"
	"net/url"
)

func basicAuth(username, password string) string {
	auth := fmt.Sprintf("%s:%s", username, password)
	basicAuth := "Basic " + base64.StdEncoding.EncodeToString([]byte(auth))
	return basicAuth
}

func proxyWithAuth(u *url.URL, username, password string) func(*http.Request) (*url.URL, error) {
	authHeader := basicAuth(username, password)
	return func(request *http.Request) (*url.URL, error) {
		request.Header.Add("Proxy-Authorization", authHeader)
		return u, nil
	}
}

func main() {
	proxyUrl, err := url.Parse("http://localhost:8080")
	if err != nil {
		panic(err)
	}
	proxy := proxyWithAuth(proxyUrl, "myusername", "mypassword")
	req.SetProxy(proxy)
}
```
pr is welcomed if you want req become more handy in proxy authentication with buitin support (with good test file)

And you can modify `cookiejar` like this:
``` go
req.Client().Jar = jar
```

**Comment by seaguest** [comment]
Hello,

I just found the http package does support proxy scheme. 

```
raw := "socks5://username:password@host:port"
req.SetProxyUrl(raw)
```
The above code works well.

Regarding the CookieJar, we may need to pass a cookiejar in some subsequent requests, it this could be handled automatically at req level, it would be quite convenient.

**Comment by imroc** [comment]
you can use req.New() to create a req client instead of default client, then you can modify the inside http.Client.Jar for some requests
