### ISSUE TITLE
why "trace is not enabled" when RemoteAddr is nil?

### ISSUE THREAD

**Issue by GingerMoon** [imroc/req#311]
Hi imroc,

May I know why "trace is not enabled" when RemoteAddr is nil?
This error message seems to be a little confusing. Please feel to let me know if a PR is needed.

func (t TraceInfo) Blame() string {
	if t.RemoteAddr == nil {
		return "trace is not enabled"
	}
...

**Comment by imroc** [comment]
TraceInfo is designed without method of pointer, if trace is not enabled, TraceInfo should be an empty struct with all empty value field, RemoteAddr is one of the field must not empty if trace is enabled, so, if trace is not enabled, RemoteAddr is nil, otherwise not nil.
