### ISSUE TITLE
看了文档之后，我知道了如何构建一个正常的请求，但如果我想构建这样的请求，请问应该怎么写才行。

### ISSUE THREAD

**Issue by qi4L** [imroc/req#316]
POST /Upload.aspx?preload=1 HTTP/1.1
Host:
Accept: */*
Accept-Encoding: gzip, deflate
Content-Length: 261
User-Agent: Mozilla/5.0 (iPod; U; CPU iPhone OS 3_0 like Mac OS X; ko-KR) AppleWebKit/535.16.4 (KHTML, like Gecko) Version/3.0.5 Mobile/8B117 Safari/6535.16.4
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryVXR9biLu
Connection: close

------WebKitFormBoundaryVXR9biLu
Content-Disposition: form-data; name="File1";filename="1.txt"
Content-Type: image/jpeg

1
------WebKitFormBoundaryVXR9biLu--

**Comment by qi4L** [comment]
我不知道怎么才能指定这个为Content-Type: image/jpeg

**Comment by imroc** [comment]
你可以调用 `SetFileUpload` 传入 `FileUpload` 对象，里面有 Content-Type 字段
