### ISSUE TITLE
关于cookie的疑问

### ISSUE THREAD

**Issue by biaosheng** [imroc/req#318]
client.cookies()命令只是从resp.headers里面获取setcookie的值
比如client提交的时候带的有cookie   testA=XXXXX
请求返回的有 testB=xxxx
使用client.cookies()只能得到testB=xxxx
怎么拿到testA呢

**Comment by imroc** [comment]
testA 是手动加的吧，手动加的没存到cookiejar里，在自己业务逻辑里可以拿

**Comment by biaosheng** [comment]
> testA 是手动加的吧，手动加的没存到cookiejar里，在自己业务逻辑里可以拿

并不是,我测试过的 我访问第一次url的时候,返回一个3个cookie  再次访问的时候返回2个(cookieName跟上面的三个重复)  用 client.cookies()提取cookie的时候 ,只能提取出来最后一次访问的2个cookie

**Comment by biaosheng** [comment]
相当于只取最后一次resp.headers 里面set-cookie的值   其他的就没有了

**Comment by imroc** [comment]
直接从 resp.Headers 里取 set-cookie 不就行了么 `resp.Header["Set-Cookie"]`
