### ISSUE TITLE
support alternative json decoder?

### ISSUE THREAD

**Issue by seaguest** [imroc/req#32]
Hello,

I found the req does use the default json decode for req.ToJSON, is it possible to support https://github.com/json-iterator/go which is more tolerant?

**Comment by imroc** [comment]
if support more decoder, I think more encoder should be supported too, but some handy API of req like `req.SetJSONEscapeHTML()`, `req.SetJSONIndent()`, `req.SetXMLIndent()` may not work after customized the encoder.
And I don't want to depend any other library, if we support customize encoder and decoder we should extract interface for decoder and encoder, users write their own decoder and encoder depend on other library, the interface should like this:
``` go
type Decoder interface{
	Decode (v interface{}) error
}
type Encoder interface{
	Encode (v interface{}) error
}
```
and req should expose API to allow customize the decoder and encoder for json and xml: `SetJsonEncoder`, `SetJsonDecoder`, `SetXmlEncoder`, `SetXmlDecoder`

Anyway, this could be implemented, but not very important I think. I'm busy recently, PR is welcomed if you are Interested

**Comment by imroc** [comment]
v2 can customize it, try and enjoy :)
