### ISSUE TITLE
Is QueryParams is a map[string]interface variable type?

### ISSUE THREAD

**Issue by therusetiawan** [imroc/req#33]
I try to make a request with query params. When i define `params` with `map[string]interface{}` variable type, req is not sending query params.

Here is the detail
```
var params map[string]interface{}
params = req.QueryParam{
	"key": "value",
}
req.Get("https://something.com/path/", params)
```

But it's work well when `params` variable type is auto assigned.
```
params := req.QueryParam{
	"key": "value",
}
req.Get("https://something.com/path/", params)
```

**Comment by imroc** [comment]
`req.QueryParam` is actually a `map[string]interface{}`, but `req.QueryParam` is a new type, you can't use `map[string]interface{}` as a `req.QueryParam` dicrectly, convert it to  `req.QueryParam`:
``` go
var params map[string]interface{}
params := map[string]interface{}{
	"key": "value",
}
p := req.QueryParam(params)
```
