### ISSUE TITLE
Add SECURITY.md

### ISSUE THREAD

**Issue by zer0yu** [imroc/req#349]
Hey there!

I am an open-source security researcher who has identified a security issue, but I am unsure of the best way to disclose it.

If not a hassle, might you kindly add a SECURITY.md file with an email or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

**Comment by imroc** [comment]
Thanks for your feedback, `SECURITY.md` is created, you can send it to [roc@imroc.cc](mailto:roc@imroc.cc)

**Comment by zer0yu** [comment]
Thank you for your response, I have emailed you the vulnerability report.

**Comment by zer0yu** [comment]
Hey Chen,

I hope this message finds you well.

I previously reported a vulnerability titled "The req library may send unintended requests when malformed URLs are provided," which has since been addressed in req v3.43.4. I appreciate your prompt action in resolving this issue.

Given the significance of this vulnerability, I would like to inquire if it would be possible to publicly disclose the vulnerability report through a GitHub advisory. Additionally, I believe assigning a CVE number to this vulnerability would facilitate better tracking and awareness within the community.

Could you please let me know your thoughts on this matter? If any further steps are required from my side to assist with the disclosure and CVE assignment process, I am more than willing to help.

Thank you for your attention to this request, and I look forward to your response.

Best regards,

**Comment by imroc** [comment]
> Given the significance of this vulnerability, I would like to inquire if it would be possible to publicly disclose the vulnerability report through a GitHub advisory. Additionally, I believe assigning a CVE number to this vulnerability would facilitate better tracking and awareness within the community.

Yes, feel free to do this.

**Comment by zer0yu** [comment]
Thank you for your prompt response and for agreeing to the disclosure through a GitHub advisory. We appreciate your cooperation in ensuring that the community is informed and can respond appropriately to the vulnerability.

Here’s a brief overview of the process for disclosing the vulnerability and applying for a CVE through GitHub Advisory:

- Create a GitHub Advisory: Go to the Security tab of your repository and select "Security Advisories". Click on "New Draft Advisory" to start the process.
-  Fill in the Advisory Details: Provide a summary of the vulnerability, affected versions, and possible mitigations. It’s important to keep the advisory initially confidential until all details are finalized.
-  Request a CVE: Within the draft advisory, you can request a CVE ID by selecting the option "Request CVE". GitHub will handle the CVE assignment through their CVE numbering authority partners.
- Publish the Advisory: Once the advisory is ready and reviewed, publish it. This makes the details public and notifies users about the vulnerability and the steps they should take.

For further details, you can refer to the official GitHub documentation on security advisories here: [GitHub Advisory Documentation](https://docs.github.com/en/code-security/security-advisories/publishing-a-security-advisory).

Thank you once again for your collaboration. Please let me know if you need any further information or assistance during the process.

Best regards,
