### ISSUE TITLE
info.FileSize empty in SetUploadCallback() when using SetFileReader()

### ISSUE THREAD

**Issue by ManuelReschke** [imroc/req#352]
Hi,
if i use SetFileReader() for uploading a file in combination with SetUploadCallback() the info.FileSize is always 0 / empty. Looks like its not a working combination? You have not implement this.

v3.43

**Comment by imroc** [comment]
Yes, it's not a working combination, cuz we can't get the file size from io.Reader interface, you should use `SetFile` or `SetFiles`

**Comment by ManuelReschke** [comment]
Ok then i will close this here. Thanks
