### ISSUE TITLE
怎么保证header不被添加内容呢

### ISSUE THREAD

**Issue by owwkmidream** [imroc/req#356]
在OnBeforeRequest中间件和DevMode dump出来的信息，都没有发现多余的header，但是使用抓包软件就看见每次都自己添加了一个
Accept-Encoding: gzip

由于客户端指纹的问题，我希望header仅出现我指定的字段，并且进行自定义排序，这个多出的Accept-Encoding: gzip破坏了指纹。

**Comment by owwkmidream** [comment]
![image](https://github.com/imroc/req/assets/50006392/74c16f37-bcfa-4d98-bb01-f928bf43bb47)
![image](https://github.com/imroc/req/assets/50006392/18e160f0-7816-437a-8eca-7a2d2bb0cabe)

最小复现示例：
```go
package main

import (
	"fmt"
	"github.com/imroc/req/v3"
	"strconv"
)

func main() {
	reqs := req.DevMode().EnableForceHTTP1()
	// 代理抓包地址
	reqs.SetProxyURL("http://127.0.0.1:9000")

	var headers = map[string]string{
		"Content-Type":     "application/json",
		"User-Agent":       "my-ua",
		"charset":          "UTF-8",
		"My-Headers":       "1.30",
		"Content-Encoding": "deflate",
		"Content-Length":   "",
		"Host":             "httpbin.org",
	}
	var data = []byte(`{"hello":"world"}`)
	headers["Content-Length"] = strconv.Itoa(len(data))

	var resp map[string]interface{}
	reqs.Post("https://httpbin.org/post").
		SetHeaderOrder(
			"Content-Type",
			"User-Agent",
			"charset",
			"Mai-Encoding",
			"Content-Encoding",
			"Content-Length",
			"Host",
		).
		SetBodyBytes(data).
		SetHeadersNonCanonical(headers).
		SetSuccessResult(&resp).
		Do()

	for k, v := range resp["headers"].(map[string]interface{}) {
		fmt.Println(k, v)
	}
}

```

**Comment by imroc** [comment]
DevMode dump 出来的是可以看到的，我用你的代码都可以

![image](https://github.com/imroc/req/assets/7448852/855f88bb-80c7-4446-8299-773c1a12d675)

**Comment by owwkmidream** [comment]
> DevMode dump 出来的是可以看到的，我用你的代码都可以
> 
> ![image](https://private-user-images.githubusercontent.com/7448852/333013335-855f88bb-80c7-4446-8299-773c1a12d675.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NDMzOTcsIm5iZiI6MTcxNjQ0MzA5NywicGF0aCI6Ii83NDQ4ODUyLzMzMzAxMzMzNS04NTVmODhiYi04MGM3LTQ0NDYtODI5OS03NzNjMWExMmQ2NzUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjNUMDU0NDU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWQ2YmNjNDcwNmMyMWFhMDIyMmIxMGZjNTIzMjM1MDMxZmZjMTRkZGE1MTg4OTJjYjY3YmNiNGQxZmU0NjUxZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.qAy0Mn6nKV1-lF0pvWV4l1yiFpNiNDqo6TmLEMuoWiQ)

是的，我复现不出来，项目里dump的信息，header后没有跟着一个空行直接就是body了，也看不见这个多出来的Accept-Encoding: gzip。

由于客户端指纹的问题，我希望header仅出现我指定的字段，这个有办法实现吗

**Comment by imroc** [comment]
> 我希望header仅出现我指定的字段，这个有办法实现吗

暂时没有这个能力，但是如果想不自动加 `Accept-Encoding` 可以这样设置下：
```go
client.DisableCompression()
```

**Comment by owwkmidream** [comment]
> > 我希望header仅出现我指定的字段，这个有办法实现吗
> 
> 暂时没有这个能力，但是如果想不自动加 `Accept-Encoding` 可以这样设置下：
> 
> ```go
> client.DisableCompression()
> ```

okk，暂时解决了，感谢。不过现在有了header order，也希望未来能够增加header仅出现指定字段的能力！！
