### ISSUE TITLE
[Vulnerability: GO-2024-2682] Denial of service via connection starvation in github.com/quic-go/quic-go

### ISSUE THREAD

**Issue by iTanken** [imroc/req#366]
```shell
go run golang.org/x/vuln/cmd/govulncheck@latest ./...
```

- Output:

    === Symbol Results ===

    Vulnerability ＃1: GO-2024-2682
        Denial of service via connection starvation in github.com/quic-go/quic-go

  - More info: https://pkg.go.dev/vuln/GO-2024-2682
  - Module: github.com/quic-go/quic-go
    - Found in: github.com/quic-go/quic-go@v0.40.1
    - Fixed in: github.com/quic-go/quic-go@v0.42.0

**Comment by mancej** [comment]
This is an issue for us as well, please fix!
