### ISSUE TITLE
HTTP2 impersonate enhancement

### ISSUE THREAD

**Issue by vellrya** [imroc/req#371]
Hello, I'm trying to understand how web apps detect that a request is sent from Go despite replacing ja3 and setting the correct http2 parameters.

Analysing the traffic in Wireshark I found that req sends HEADERS and DATA in different frames. I have previously come across that some systems use this mechanism to determine the trustworthiness of the request as the original java library combines them (https://github.com/grpc/grpc-go/issues/6850). 

Can you please suggest a way for req to combine headers and data into one frame?
Need a simple and dirty way to not waste your time but test the assumption)

**Comment by imroc** [comment]
According to the HTTP2 specification, header and data are different frames, and also req does not support sent them in the same frame.

**Comment by vellrya** [comment]
Thanks for the reply!
Apparently the authors of okhttp didn't read the spec very carefully, because in practice most android apps use this library, which combines headers and data into one frame. In my opinion, this is quite a relevant feature to determine the trustworthiness of a request.
![image](https://github.com/imroc/req/assets/13716114/71fe1a1f-c7bb-40f4-93e2-e435afa846eb)
(Android app traffic)

You know the structure of req better than anyone else, so I'd appreciate your advice on whether there is a way to modify the req code to experiment whether merging into a single frame can help a request to be successfully sent.

**Comment by vellrya** [comment]
Since there is no simple solution, there is no need to waste time on it)
