### ISSUE TITLE
如何优雅处理响应返回的类型不确定

### ISSUE THREAD

**Issue by pysyw** [imroc/req#383]
请问下大佬，如何处理请求相应回来的数据类型不固定，
有可能是 `{"a":1,b:2}` ，也有可能是 `{"a":"1",b:"2"}`
目前我的是以 
`type A struct {  A any, B any }`  赋值any来处理的，请问下大佬还有没有其他优雅的处理方案，比如我已经确认这个值只可能是string或者int。

**Comment by imroc** [comment]
可以考虑结合 gjson 来做，参考 https://req.cool/zh/docs/tutorial/handle-response/#%E7%BB%93%E5%90%88-gjson-%E8%BD%BB%E6%9D%BE%E8%8E%B7%E5%8F%96-json-%E5%AD%97%E6%AE%B5

对于类型不确定的字段，可以用 gjson 来获取 value，根据 value 的 Type （String 或 Number https://pkg.go.dev/github.com/tidwall/gjson#Type）来调用相应的方法获取值。

**Comment by XiaoK29** [comment]
> 请问下大佬，如何处理请求相应回来的数据类型不固定， 有可能是 `{"a":1,b:2}` ，也有可能是 `{"a":"1",b:"2"}` 目前我的是以 `type A struct { A any, B any }` 赋值any来处理的，请问下大佬还有没有其他优雅的处理方案，比如我已经确认这个值只可能是string或者int。

如果确定的话可以使用泛型去做的，在声明的时候给类型
```go
type IntOrStr interface {
	~string | ~int
}

type Test[K, V IntOrStr] struct {
	A K
	B V
}

jsonStr := `{"a":1,b:2}`
t := Test[int, int]{}
json.Unmarshal([]byte(jsonStr), &t)
```
