### ISSUE TITLE
Access Pseudo Headers?

### ISSUE THREAD

**Issue by adaml881** [imroc/req#398]
Is there any way (after the request is sent) that I can get Pseudo headers that were sent in the request + any response pseudo headers?

**Comment by imroc** [comment]
Why not just read Request/Response's fields?

* `Request.URL.Schema`: `:schema`
* `Request.URL.RawPath`: `:path`
* `Request.Host`: `:authority`
* `Request.Method`: `:method`
* `Response.Status`:  `:status`

**Comment by adaml881** [comment]
I could, I just wanted the exact raw headers that were sent, and in the same order they were sent. I've acheived it using the EnableDumpWithoutBody() feature. Thanks :)
