### ISSUE TITLE
上传文件设置header头中Content-Type无效

### ISSUE THREAD

**Issue by kayw-geek** [imroc/req#40]
```func postFile(filename string, targetUrl string) error {
	req.Debug = true
    //打开文件句柄操作
	// file, _ := os.Open(filename)
	progress := func(current, total int64) {
		fmt.Println(float32(current)/float32(total)*100, "%")
	}
	authHeader := req.Header{
		"User-Agent": "Go-http-client/1.2",
		"Content-Type": "image/png",
	}
	req.Post(tinypngPushApi,authHeader, req.File(filename),req.UploadProgress(progress))
    return nil
}
```
### debug
2.4035301 %
POST /web/shrink HTTP/1.1
Host: tinypng.com
User-Agent: Go-http-client/1.2
Transfer-Encoding: chunked
Content-Type: multipart/form-data; boundary=bbc4ac77ebd45833cb74d9971017228148c453e4bfa38de6bc1eb77c7bc3
Accept-Encoding: gzip

--d05faa4986965b6bed833f966fd22a11adeb86dd774685c41bd33996af04
Content-Disposition: form-data; name="media"; filename="e.png"
Content-Type: application/octet-stream

******
--d05faa4986965b6bed833f966fd22a11adeb86dd774685c41bd33996af04--

=================================

HTTP/2.0 415 Unsupported Media Type
Content-Length: 73
Alt-Svc: clear
Content-Type: application/json
Date: Wed, 14 Aug 2019 03:14:11 GMT
Via: 1.1 google

{"error":"unsupported_media_type","message":"File type is not supported"}

**Comment by YiuTerran** [comment]
遇到同样的问题，所以我提了个PR #55
