### ISSUE TITLE
Make possible to set Debug for specific client.

### ISSUE THREAD

**Issue by dennypenta** [imroc/req#42]
I have a few services in my project.
So I wanna set Debug for one of them.
What do you think of inject debug flag in the Req client?

But it seems hard for compatibility with current implementation.
I mean, if we have set one of them, what to do?

Now I need to change this value before and after each request, it doesn't thread-safe.

**Comment by YongHaoWu** [comment]
@dennypenta It is a strange need. Why u need so custom log enable?

**Comment by imroc** [comment]
You can set flags for specific req client, and get the debug string by calling `resp.Dump()`, and log it to anywhere you want, here is a example:
``` go
r := req.New()
r.SetFlags(req.LstdFlags)
resp, _ := r.Get()
str := resp.Dump()
log.Println(str)
```

**Comment by dennypenta** [comment]
@imroc ye, it's a solution. But if I will have injected field debug, I can customise logging in each http client individually
