### ISSUE TITLE
net/http: HTTP/1.x transport connection broken: http: ContentLength=431 with Body length 667

### ISSUE THREAD

**Issue by joselbr2099** [imroc/req#45]
I am trying to upload a file to my server, but when I try to upload the file I get this:

    error-->  Post http://127.0.0.1:2047/ctrl/upload: net/http: HTTP/1.x transport connection broken: http: ContentLength=431 with Body length 667
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0x6bbc2c]

This is the client code:

    package ctrl

    import (
        "fmt"
        "os"
	    "github.com/imroc/req"
	    "strings"
	    "strconv"
    )

    func UploadFile(file_up string){

       //get file info
	   fileInfo, err := os.Stat(file_up)
       if err!=nil{
		 fmt.Println(err)
	    }

	   file, _ := os.Open(file_up)
	   upload:= req.FileUpload{
		   	File:      file,
		   	FieldName: "file",
		   	FileName:  fileInfo.Name(),
	   }

       //set header
	   header := req.Header{
		   "Content-Type":  "multipart/form-data",
		   "Authorization": "BEARER "+readKey(), 
		   "Content-Length": strconv.FormatInt(fileInfo.Size(),10), //convert bytes to string
	   }
	
	   defer file.Close()

       //set progress
	   progress := func(current, total int64) {
		   fmt.Println(float32(current)/float32(total)*100, "%")
	   }
	
   	r,err:=req.Post("http://127.0.0.1:2047/ctrl/upload",upload,header,req.UploadProgress(progress))
	   if err != nil {
		   fmt.Println("error--> ",err)
	   }

   	fmt.Println(r.String())
	   resp := r.Response()
	   r.Response().Body.Close()
	   fmt.Println(resp.StatusCode)
} 

The line that causes the problem is:

    "Content-Length": strconv.FormatInt(fileInfo.Size(),10),

when I remove that line everything works fine, but the server log tells me this for each file uploaded

    Content-Length = -1

and I need real Content-Length of each file for the record in the db

**Comment by imroc** [comment]
There is no Content-Length been calculated using multipart upload, and you can not get the real length just using file size, body form binary field will be encoded as base64. You can just record file size in db, but do not set Content-Length to request.

**Comment by Odyssey2247** [comment]
It's true, I'm wrong, what I'm trying to do is get something like: req.ContentLength
