### ISSUE TITLE
can't set query params and body together

### ISSUE THREAD

**Issue by fuxiaohei** [imroc/req#5]
```
--- POST http://localhost:8080/api?data1=data1&data2=data2
body content
```

it seems no way to send request like this.

**Comment by imroc** [comment]
of course you can't do this, because if you post, your body could be json or something else, which can not mix with params. you should write params in the url instead.

**Comment by imroc** [comment]
`req` support it now, use `req.QueryParam{}`, force append params at the end of the url. for example:
``` go
req.Post("http://localhost:8080/api", req.QueryParam{"data1" : "data1", "data2" : "data2"}, "body content")
