### ISSUE TITLE
抄了一系列viper的接口

### ISSUE THREAD

**Issue by ruolinn** [imroc/req#54]
是不是可以考虑给这个包添一些类似viper的操作  这样获取回json数据后直接可以操作里面的值。

例如
`package main

import (
	"fmt"

	"github.com/ruolinn/req"
)

/*
{
  "id": 1,
  "name": "Leanne Graham",
  "username": "Bret",
  "email": "Sincere@april.biz",
  "address": {
    "street": "Kulas Light",
    "suite": "Apt. 556",
    "city": "Gwenborough",
    "zipcode": "92998-3874",
    "geo": {
      "lat": "-37.3159",
      "lng": "81.1496"
    }
  },
  "phone": "1-770-736-8031 x56442",
  "website": "hildegard.org",
  "company": {
    "name": "Romaguera-Crona",
    "catchPhrase": "Multi-layered client-server neural-net",
    "bs": "harness real-time e-markets"
  }
}
*/

func main() {
	rsp, _ := req.Get("https://jsonplaceholder.typicode.com/users/1")

	fmt.Println(rsp.GetFloat64("address.geo.lng"))
}
`
我fork作者的库有过修改, 不知道这样合不合法 因为也是自己用，如果有冒犯的作者  我这边后面删除。

**Comment by imroc** [comment]
想法很好，欢迎试用最新v2版，后续考虑下支持
