### ISSUE TITLE
关于重定向

### ISSUE THREAD

**Issue by Alberthchang** [imroc/req#56]
这个库有没有可以设置不跟随重定向的选项啊，我访问不想跟随302跳转

**Comment by imroc** [comment]
你可以自定义 302 的重定向的处理函数
``` go
package main

import (
 "errors"
 "github.com/imroc/req"
 "net/http"
)

func main() {
 r := req.New()
 client := &http.Client{
  CheckRedirect: checkRedirect,
 }
 r.SetClient(client)
 r.Get("https://www.baidu.com")

}
func checkRedirect(req *http.Request, via []*http.Request) error {
 return errors.New("stopped all redirects")
}
```

**Comment by 23233** [comment]
@imroc  但是即使是设置了自定义302处理函数 也只能返回 nil或者一个error 如果返回了一个error 那么请求的resp并不能获取到 也就是说 我本来是想获取到 一个请求302的重定向地址以及请求的信息 现在都无法获取了呢?

**Comment by valetanddama** [comment]
@23233 maybe it helps you
`
req.SetClient(&http.Client{
		CheckRedirect: func(req *http.Request, via []*http.Request) error {
			return http.ErrUseLastResponse
		},
})
`

**Comment by 23233** [comment]
@valetanddama Nice,thanks~

**Comment by vintingb** [comment]
> 你可以自定义 302 的重定向的处理函数
> 
> ```go
> package main
> 
> import (
>  "errors"
>  "github.com/imroc/req"
>  "net/http"
> )
> 
> func main() {
>  r := req.New()
>  client := &http.Client{
>   CheckRedirect: checkRedirect,
>  }
>  r.SetClient(client)
>  r.Get("https://www.baidu.com")
> 
> }
> func checkRedirect(req *http.Request, via []*http.Request) error {
>  return errors.New("stopped all redirects")
> }
> ```

自定义302处理函数之后,我应该筑梦恢复默认的
