### ISSUE TITLE
req.Param{}不支持struct中json tag

### ISSUE THREAD

**Issue by duke-git** [imroc/req#64]
我需要从struct转为req.Param{}，但是req.Param{}不支持struct中json tag。
struct param {
    UserId           *string `json:"userId" `
}
reqParam := req.Param{}

for k, v := range param {
	reqParam[k] = v
}

fmt.Println(reqParam) //reqParam是{"UserId": xxx} 需要的是{"userId": xxx}

**Comment by imroc** [comment]
支持的，fmt.Println支持打印结构体，不是发送请求
