### ISSUE TITLE
发送post请求，设置header 为content-type: application/json, req.go中重置为application/x-www-form-urlencode 导致400参数格式错误

### ISSUE THREAD

**Issue by duke-git** [imroc/req#66]
![image](https://user-images.githubusercontent.com/5037603/100302608-ad7b2380-2fd5-11eb-9805-c1a960c9f1f9.png)
![Uploading image.png…]()

**Comment by imroc** [comment]
如果是用json，可以这样用:
``` go
req.Post(url, req.BodyJSON(&foo))
```
