### ISSUE TITLE
req.POST throws EOF, when the previous request fails

### ISSUE THREAD

**Issue by samarthgr** [imroc/req#69]
I have a function which calls `resp, err := req.Post(url, req.BodyJSON(requestJson))` for each row in CSV to ingest data. When one of the requests fails (for genuine reason),  the subsequent post call (most of the time only 1st call after the failed request) throws EOF even though there is no issues with data. This is not consistent though.

But, while testing I saw if we use `req.New()` and use this to post then the above error is not reproducible.

Is this expect? and also are there any implications if we use `req.New()` for each request instead of `req.Post()` method?

**Comment by imroc** [comment]
Did you read the body? If not, requests might not been closed.

**Comment by samarthgr** [comment]
Yes, I have read the body of the failed request with `resp.Bytes()`
