### ISSUE TITLE
req 添加Header 会规范HeaderKey

### ISSUE THREAD

**Issue by Carrotxyy** [imroc/req#72]
req 在添加header 时，都是通过http.Header.Add(key, value) 添加，这使得我无法添加小写开头的Key
请问我该如何解决？

**Comment by CoderCharm** [comment]
`http` 请求 `header`里面的参数是不区分大小写的，可以参考 [developer.mozilla.org](https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Headers)

**Comment by Carrotxyy** [comment]
![image](https://user-images.githubusercontent.com/56505011/115532442-5c433780-a2c8-11eb-8453-00c6c7905817.png)
当使用 Header.Add 或 Header.Set 是会自动转成大写开头的**Key**
虽然规范是首字母大写，但对接的系统需要识别的字段是小写
用postman测试时也是这样的情况，
小写**key**是可以正常调用的
如果换成大写**Key**则调用失败

**Comment by CoderCharm** [comment]
那只能说明，对接的那一方不规范。 https://stackoverflow.com/questions/5258977/are-http-headers-case-sensitive
