### ISSUE TITLE
How to use Basic Auth and if possible digest auth

### ISSUE THREAD

**Issue by sunshine69** [imroc/req#74]
Hi,

in the doco there is no example, etc, I wish that it would be possible and added some documentation of how to.

Thanks

**Comment by sunshine69** [comment]
Or extract the http.Client and use it which defeat the purpose of `easy front end` :smile:

**Comment by imroc** [comment]
let me give you a example:
```go
func getAuthHeader(username, password string) req.Header {
	auth := username + ":" + password
	return req.Header{
		"Authorization": "Basic " + base64.StdEncoding.EncodeToString([]byte(auth)),
	}
}

func main() {
	auth := getAuthHeader("admin", "123456")
	req.Get("https://imroc.cc", auth)
}
```

**Comment by sunshine69** [comment]
My point is, I already did like this but after refreshing (google search about the Authorizationheader etc etc). Admit it is 15 minutes job but it would be nicer to just include and give it a syntactic sugar for it ...

**Comment by sunshine69** [comment]
Found that you update the example with this. Greato! that saves some times searching.
