### ISSUE TITLE
Set time out doesn't work

### ISSUE THREAD

**Issue by shuhrat-shokirov** [imroc/req#75]
Hi,

Thank you so much for the great package. 

I had one problem with the time out and panicking and I used what you suggested above. 
The problem I faced now is the request still takes a long time more than I expected. 

```
r := req.New()
r.SetTimeout(1*time.Second)

resp, err := r.Post(url, header, req.BodyJSON(request))
```

30.002710879s

**Comment by imroc** [comment]
I think it's impossible. Can you record time consumption only for the request ? 
```go
startTime := time.Now()
resp, err := r.Post(url, header, req.BodyJSON(request))
duration := time.Since(startTime)
fmt.Println("time cost: ", duration)
```
