### ISSUE TITLE
request header 不支持map[string]interface{}

### ISSUE THREAD

**Issue by duke-git** [imroc/req#76]
header类型为map[string]interface{}，发现请求时无法设置header，必须为map[string]string吗，我的header里面value会有int, int64类型（时间戳）
![Uploading screenshot-20210623-163808.png…]()

**Comment by duke-git** [comment]
![screenshot-20210623-163808](https://user-images.githubusercontent.com/5037603/123073645-2eee4380-d449-11eb-832c-6698283ab16f.png)

**Comment by imroc** [comment]
欢迎试用最新v2版
