### ISSUE TITLE
v2 build error

### ISSUE THREAD

**Issue by freemanpolys** [imroc/req#84]
Hi,
I'm having issue when testing the new version : **main.go:3:8: //go:build comment without // +build comment**

```
package main

import "github.com/imroc/req/v2"

func main() {
req.DevMode()
req.Get("https://api.github.com/users/imroc")

}
```
File : main.go

```
module testo

go 1.16

require github.com/imroc/req/v2 v2.0.4
```
File: go.mod

**Comment by imroc** [comment]
Thanks for you feedback, it's the build tag that go1.17 introduced which is unsupported in go1.16 and lower go version, and have been fixed in the latest version(2.0.5)
