### ISSUE TITLE
Dumping single request

### ISSUE THREAD

**Issue by BrianLeishman** [imroc/req#87]
Is there any way to get the dump output for just a single request? Like how in V1 you could use `fmt.Sprintf("%+v", resp)` for example.

**Comment by imroc** [comment]
Not currently supported, will be considered later

**Comment by BrianLeishman** [comment]
As a work around/middle ground, I proposed two PRs:

https://github.com/imroc/req/pull/88
https://github.com/imroc/req/pull/89

I separated them because I think the first one is very straight forward, whereas the second one possibly has performance implications or has different implementation details in mind

**Comment by imroc** [comment]
Thanks  but there is a better implementation already work in progress.

**Comment by BrianLeishman** [comment]
Awesome, looking forward to it

**Comment by imroc** [comment]
Dumping single request is supported now, some API-incompatible changes was involved during refactoring, so the latest version is v3 now, checkout the document: https://github.com/imroc/req#debugging

**Comment by BrianLeishman** [comment]
That was fast! Looks awesome, thank you!
