### ISSUE TITLE
SetQueryString panics

### ISSUE THREAD

**Issue by abdukhashimov** [imroc/req#90]
I had a case when I need to send the query and calculated hash. As a result I decided to implement function that calculates the hash and returns the query parameters in the exact order when hash calculated. Wanted to use `SetQueryString` and it panics
![image](https://user-images.githubusercontent.com/57385309/152729727-5ead26d8-53d5-4d80-bea1-dcbbc675ec56.png)

As far as I understand, what it is trying to do is as follows. It is trying to access QueryParams which is null.
![image](https://user-images.githubusercontent.com/57385309/152729861-a0d8bf92-668c-450c-8f3e-cd5adea20ccf.png)

It should have supposed to work I think, because it could parse the whole parameters without any issue.
![image](https://user-images.githubusercontent.com/57385309/152729959-7586b0b4-1fc1-4b03-88e4-990c99f3600b.png)

May be the solution is to create the queryparams if it is null

**Comment by imroc** [comment]
Thanks for your feedback, it's been fixed in https://github.com/imroc/req/commit/48e2904e9560abbe0d3549bd8f21dad8b13c4fdc

**Comment by imroc** [comment]
You can upgrade to the latest version (v3.2.1)
