### ISSUE TITLE
response formatted

### ISSUE THREAD

**Issue by sunhis** [imroc/req#92]
Hello,The response can be formatted for subsequent consideration

**Comment by imroc** [comment]
Do you mean that the contents of the dump can be custom formatted? This capability can be added later without breaking change. Most people don't need it, for now, we should focus on other high-priority needs.

**Comment by sunhis** [comment]
This is a small point. Thank you for your answer

**Comment by sunhis** [comment]
This is a small point. Thank you for your answer
