### ISSUE TITLE
Usage with gock or httpmock

### ISSUE THREAD

**Issue by raine** [imroc/req#93]
Could this be used with [gock](https://github.com/h2non/gock) or [httpmock](https://github.com/jarcoal/httpmock) if `http.Client` was exposed?

https://github.com/imroc/req/blob/addfc5e4066371fec476901de23e98b87544c7b7/client.go#L60

https://github.com/jarcoal/httpmock#ginkgo--resty-example

```go
httpmock.ActivateNonDefault(resty.DefaultClient.GetClient())
```

resty exposes `http.Client` so it can be used with httpmock.

**Comment by imroc** [comment]
Good idea, the `http.Client` is exposed now (v3.8.0).
