### ISSUE TITLE
Retry Hook Update Field

### ISSUE THREAD

**Issue by wsuppiger** [imroc/req#98]
Hi, I was wondering if it is possible to call `SetBearerToken` or `SetHeaders` in a retry hook for the next request.  I am trying to update the bearer token if there is a 401 error, but as on now, `resp.Request.SetBearerAuthToken(new_token)` does not update the request with the new token for the next request.

**Comment by imroc** [comment]
This is exactly what I want to do in the next release, it is currently supported in [this commit](https://github.com/imroc/req/commit/0e11a197680fc27ac9aabf11e189340aaa958d43)

**Comment by imroc** [comment]
Released in v3.9.2

**Comment by wsuppiger** [comment]
Awesome, thanks!
