### ISSUE TITLE
3.9.3编译错误

### ISSUE THREAD

**Issue by tmphuang6** [imroc/req#99]
go get github.com/imroc/req/v3
go: github.com/imroc/req/v3 upgrade => v3.9.3
# github.com/imroc/req/v3
go/pkg/mod/github.com/imroc/req/v3@v3.9.3/h2_not_go115.go:11:49: undefined: context
go/pkg/mod/github.com/imroc/req/v3@v3.9.3/h2_not_go115.go:11:93: undefined: tls
go/pkg/mod/github.com/imroc/req/v3@v3.9.3/h2_not_go115.go:12:13: undefined: tls
go/pkg/mod/github.com/imroc/req/v3@v3.9.3/h2_transport.go:409:45: undefined: os.ErrDeadlineExceeded

**Comment by imroc** [comment]
看来你的go版本较低，请问是哪个版本？

**Comment by imroc** [comment]
查了下，`os.ErrDeadlineExceeded` 是 go1.15 引入的，我修改下 `go.mod`要求，至少go1.15以上

**Comment by imroc** [comment]
已更新`go.mod`([update go.mod: require go1.15](https://github.com/imroc/req/commit/69fc4bbb230a6295e6c7e7a4f0d4812a5c781c80))，你可以升级下go版本来解决。

**Comment by tmphuang6** [comment]
ok
